# Generated by Django 5.2.2 on 2025-07-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileorder',
            name='download_click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='다운로드 클릭 횟수'),
        ),
        migrations.AddField(
            model_name='fileorder',
            name='download_clicked',
            field=models.BooleanField(default=False, verbose_name='다운로드 버튼 클릭 여부'),
        ),
        migrations.AddField(
            model_name='fileorder',
            name='download_clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='다운로드 버튼 첫 클릭 시간'),
        ),
    ]
