# Generated by Django 5.2.2 on 2025-07-14 23:54

import file.models
import storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_fileorder_download_click_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfile',
            name='file',
            field=models.FileField(storage=storage.backends.S3Storage(), upload_to='digital_files/%Y/%m/%d/', validators=[file.models.validate_file_size], verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, storage=storage.backends.S3Storage(), upload_to='digital_files/previews/%Y/%m/%d/', verbose_name='미리보기 이미지'),
        ),
    ]
