# Generated by Django 5.2.2 on 2025-07-18 06:41

import file.models
import storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_add_s3_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfile',
            name='file',
            field=models.FileField(storage=storage.backends.S3Storage(), upload_to=file.models.digital_file_upload_to, validators=[file.models.validate_file_size], verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, storage=storage.backends.S3Storage(), upload_to=file.models.preview_image_upload_to, verbose_name='미리보기 이미지'),
        ),
    ]
