# Generated by Django 5.2.2 on 2025-07-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_add_browse_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='digitalfile',
            name='file_store_deleted_idx',
        ),
        migrations.RemoveIndex(
            model_name='digitalfile',
            name='file_store_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='digitalfile',
            name='file_price_display_idx',
        ),
        migrations.RemoveIndex(
            model_name='digitalfile',
            name='file_hash_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileorder',
            name='file_order_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileorder',
            name='file_order_composite_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileorder',
            name='file_order_browse_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileorder',
            name='file_order_confirmed_idx',
        ),
    ]
