# Generated by Django 5.2.2 on 2025-09-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_remove_digitalfile_file_store_deleted_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileorder',
            index=models.Index(fields=['status', '-confirmed_at'], name='file_fileor_status_fc4bb0_idx'),
        ),
    ]
