# Generated by Django 5.2.2 on 2025-09-25 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_fileorder_file_fileor_status_fc4bb0_idx'),
        ('stores', '0026_store_stores_stor_email_e_ff14a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='digitalfile',
            index=models.Index(fields=['price_display'], name='file_digita_price_d_79c941_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalfile',
            index=models.Index(fields=['is_discounted'], name='file_digita_is_disc_da7c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalfile',
            index=models.Index(fields=['is_temporarily_closed'], name='file_digita_is_temp_11a61a_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalfile',
            index=models.Index(fields=['store', 'is_discounted'], name='file_digita_store_i_2a4361_idx'),
        ),
        migrations.AddIndex(
            model_name='fileorder',
            index=models.Index(fields=['is_discounted'], name='file_fileor_is_disc_5bc305_idx'),
        ),
        migrations.AddIndex(
            model_name='fileorder',
            index=models.Index(fields=['download_clicked'], name='file_fileor_downloa_3ab67a_idx'),
        ),
    ]
