# Generated by Django 5.2.2 on 2025-11-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_digitalfile_file_digita_price_d_79c941_idx_and_more'),
        ('ln_payment', '0005_paymenttransaction_file_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManualPaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '수동 저장 결제',
                'verbose_name_plural': '수동 저장 결제',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.manualpaymenttransaction',),
        ),
        migrations.CreateModel(
            name='FileOrderItemReservation',
            fields=[
            ],
            options={
                'verbose_name': '재고 예약',
                'verbose_name_plural': '재고 예약',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.orderitemreservation',),
        ),
        migrations.CreateModel(
            name='FilePaymentStageLog',
            fields=[
            ],
            options={
                'verbose_name': '결제 단계 로그',
                'verbose_name_plural': '결제 단계 로그',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymentstagelog',),
        ),
        migrations.CreateModel(
            name='FilePaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '결제 트랜잭션',
                'verbose_name_plural': '결제 트랜잭션',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymenttransaction',),
        ),
    ]
