# Generated by Django 5.2.2 on 2025-11-03 23:29

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='계약서 이름 (예: 표준 직거래 계약서)', max_length=120)),
                ('version_label', models.CharField(help_text='버전/개정 정보 (예: 2024.05 신의성실 개정판)', max_length=80)),
                ('content', models.TextField(help_text='계약 본문을 마크다운(MD) 형식으로 작성합니다.')),
                ('is_selected', models.BooleanField(default=False, help_text='계약 조건 입력 화면에서 노출할 계약서라면 체크하세요. 동시에 하나만 선택됩니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '거래 계약서',
                'verbose_name_plural': '거래 계약서',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contracttemplate',
            constraint=models.UniqueConstraint(
                condition=Q(is_selected=True),
                fields=('is_selected',),
                name='expert_single_selected_contract_template',
            ),
        ),
    ]
