# Generated by Django 5.2.2 on 2025-11-03 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_contracttemplate_expertemailsettings_and_more'),
        ('myshop', '0025_sitesettings_expert_email_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEmailSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Expert 계약 이메일 설정',
                'verbose_name_plural': 'Expert 계약 이메일 설정',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myshop.sitesettings',),
        ),
        migrations.RemoveConstraint(
            model_name='contractparticipant',
            name='unique_contract_participant',
        ),
        migrations.AlterUniqueTogether(
            name='contractparticipant',
            unique_together={('contract', 'user')},
        ),
    ]
