# Generated by Django 5.2.2 on 2025-11-03 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_contracttemplate_expertemailsettings_and_more'),
        ('myshop', '0025_sitesettings_expert_email_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEmailSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Expert 계약 이메일 설정',
                'verbose_name_plural': 'Expert 계약 이메일 설정',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myshop.sitesettings',),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE expert_contractparticipant DROP CONSTRAINT IF EXISTS unique_contract_participant;",
            reverse_sql="ALTER TABLE expert_contractparticipant ADD CONSTRAINT unique_contract_participant UNIQUE (contract_id, user_id);",
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'expert_contractparticipant_contract_id_user_id_c2c1569d_uniq'
                ) THEN
                    ALTER TABLE expert_contractparticipant
                    ADD CONSTRAINT expert_contractparticipant_contract_id_user_id_c2c1569d_uniq
                    UNIQUE (contract_id, user_id);
                END IF;
            END$$;
            """,
            reverse_sql="""
            ALTER TABLE expert_contractparticipant
            DROP CONSTRAINT IF EXISTS expert_contractparticipant_contract_id_user_id_c2c1569d_uniq;
            """,
        ),
    ]
