# Generated by Django 5.2.2 on 2025-11-04 22:19

import django.db.models.deletion
import expert.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_expertemailsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('payload', models.JSONField(help_text='계약 입력값 전체 스냅샷(JSON).')),
                ('creator_role', models.CharField(choices=[('client', '의뢰자'), ('performer', '수행자')], max_length=16)),
                ('counterparty_role', models.CharField(choices=[('client', '의뢰자'), ('performer', '수행자')], max_length=16)),
                ('status', models.CharField(choices=[('pending_counterparty', '상대방 입력 대기'), ('counterparty_in_progress', '상대방 진행 중'), ('completed', '계약 완료')], default='pending_counterparty', max_length=32)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('counterparty_email', models.EmailField(blank=True, max_length=254)),
                ('creator_signature', models.ImageField(blank=True, upload_to='contracts/signatures/')),
                ('counterparty_signature', models.ImageField(blank=True, upload_to='contracts/signatures/')),
                ('creator_signed_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty_signed_at', models.DateTimeField(blank=True, null=True)),
                ('creator_hash', models.CharField(blank=True, max_length=64)),
                ('counterparty_hash', models.CharField(blank=True, max_length=64)),
                ('mediator_hash', models.CharField(blank=True, max_length=64)),
                ('creator_hash_meta', models.JSONField(blank=True, default=dict)),
                ('counterparty_hash_meta', models.JSONField(blank=True, default=dict)),
                ('mediator_hash_meta', models.JSONField(blank=True, default=dict)),
                ('email_delivery', models.JSONField(blank=True, default=expert.models.default_email_delivery)),
                ('final_pdf', models.FileField(blank=True, upload_to='contracts/final_pdfs/')),
                ('final_pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'unique_contract_participant'
                        ) THEN
                            ALTER TABLE expert_contractparticipant DROP CONSTRAINT unique_contract_participant;
                        END IF;

                        IF EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'expert_contractparticipant_contract_id_user_id_c2c1569d_uniq'
                        ) THEN
                            ALTER TABLE expert_contractparticipant DROP CONSTRAINT expert_contractparticipant_contract_id_user_id_c2c1569d_uniq;
                        END IF;
                    END$$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'unique_contract_participant'
                        ) THEN
                            ALTER TABLE expert_contractparticipant
                            ADD CONSTRAINT unique_contract_participant UNIQUE (contract_id, user_id);
                        END IF;
                    END$$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='contractparticipant',
                    name='unique_contract_participant',
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contractparticipant',
            unique_together={('contract', 'user')},
        ),
        migrations.AddField(
            model_name='directcontractdocument',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_contracts_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
