# Generated by Django 5.2.2 on 2025-11-07 04:32

import os

from django.core.files.base import ContentFile
from django.db import migrations, models
from django.utils import timezone

from storage.utils import upload_file_to_s3


SIGNATURE_PREFIX = "expert/contracts/signatures"


def migrate_signature_files(apps, schema_editor):
    DirectContractDocument = apps.get_model("expert", "DirectContractDocument")
    for document in DirectContractDocument.objects.all().iterator():
        assets = document.signature_assets or {}
        changed = False
        for role, field_name in (("creator", "creator_signature"), ("counterparty", "counterparty_signature")):
            field = getattr(document, field_name, None)
            if not field or not field.name:
                continue
            try:
                field.open("rb")
                content = field.read()
            except FileNotFoundError:
                continue
            finally:
                try:
                    field.close()
                except Exception:
                    pass
            if not content:
                continue
            file_obj = ContentFile(content)
            original_name = os.path.basename(field.name)
            file_obj.name = original_name
            upload_result = upload_file_to_s3(file_obj, prefix=SIGNATURE_PREFIX)
            file_obj.close()
            if not upload_result.get("success"):
                continue
            assets[role] = {
                "path": upload_result.get("file_path"),
                "url": upload_result.get("file_url"),
                "size": upload_result.get("file_size"),
                "original_name": upload_result.get("original_name") or original_name,
                "storage": upload_result.get("storage", "s3"),
                "uploaded_at": timezone.now().isoformat(),
            }
            field.delete(save=False)
            setattr(document, field_name, "")
            changed = True
        if changed:
            document.signature_assets = assets
            document.save(
                update_fields=["signature_assets", "creator_signature", "counterparty_signature", "updated_at"]
            )


def noop_reverse(apps, schema_editor):
    """Reversing would require deleting assets on S3; keep existing state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_directcontractdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontractdocument',
            name='signature_assets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(migrate_signature_files, noop_reverse),
    ]
