# Generated by Django 5.2.2 on 2025-11-08 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_directcontractdocument_signature_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectContractStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stage', models.CharField(choices=[('draft', '드래프트'), ('role_one', '역할 1 서명'), ('role_two', '역할 2 서명'), ('completed', '계약 완료')], max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='expert.directcontractdocument')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
