# Generated by Django 5.2.2 on 2025-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_directcontractstagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text="여러 설정을 둘 수 있도록 식별자(기본값은 'default').", max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='활성화 시 계약 진행 전에 설정된 금액 결제가 필요하다는 정책을 안내합니다.')),
                ('client_fee_sats', models.PositiveIntegerField(default=0, help_text='의뢰자가 부담해야 하는 사토시 금액. 0이면 무료.')),
                ('performer_fee_sats', models.PositiveIntegerField(default=0, help_text='수행자가 부담해야 하는 사토시 금액. 0이면 무료.')),
                ('description', models.TextField(blank=True, help_text='결제 정책에 대한 참고 메모.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직접 계약 결제 정책',
                'verbose_name_plural': '직접 계약 결제 정책',
            },
        ),
    ]
