# Generated by Django 5.2.2 on 2025-11-08 09:07

import storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_contractpricingsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcontractdocument',
            name='counterparty_signature',
            field=models.ImageField(blank=True, storage=storage.backends.S3Storage(), upload_to='contracts/signatures/'),
        ),
        migrations.AlterField(
            model_name='directcontractdocument',
            name='creator_signature',
            field=models.ImageField(blank=True, storage=storage.backends.S3Storage(), upload_to='contracts/signatures/'),
        ),
        migrations.AlterField(
            model_name='directcontractdocument',
            name='final_pdf',
            field=models.FileField(blank=True, storage=storage.backends.S3Storage(), upload_to='contracts/final_pdfs/'),
        ),
    ]
