# Generated by Django 5.2.2 on 2025-11-10 08:49

import storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_directcontractdocument_payment_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcontractdocument',
            name='final_pdf',
            field=models.FileField(blank=True, storage=storage.backends.S3Storage(), upload_to='expert/contracts/final_pdfs/'),
        ),
    ]
