# Generated by Django 5.2.2 on 2025-11-11 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_alter_directcontractdocument_final_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontractdocument',
            name='counterparty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_contracts_signed', to=settings.AUTH_USER_MODEL),
        ),
    ]
