# Generated by Django 5.2.2 on 2025-11-11 00:58

import hashlib

from django.db import migrations, models


def populate_pdf_hash(apps, schema_editor):  # pragma: no cover - data migration
    Document = apps.get_model('expert', 'DirectContractDocument')
    for document in Document.objects.exclude(final_pdf=''):
        file_field = document.final_pdf
        if not file_field:
            continue
        storage = file_field.storage
        try:
            if not storage.exists(file_field.name):
                continue
        except Exception:
            continue
        try:
            file_field.open('rb')
        except Exception:  # pragma: no cover - missing files in storage should be skipped
            continue
        try:
            digest = hashlib.sha256()
            for chunk in iter(lambda: file_field.read(1024 * 1024), b''):
                if not chunk:
                    break
                digest.update(chunk)
            document.final_pdf_hash = digest.hexdigest()
            document.save(update_fields=['final_pdf_hash'])
        finally:
            file_field.close()


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0011_directcontractdocument_counterparty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontractdocument',
            name='final_pdf_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(populate_pdf_hash, migrations.RunPython.noop),
    ]
