# Generated by Django 5.2.2 on 2025-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_directcontractdocument_final_pdf_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertBlinkRevenueStats',
            fields=[
            ],
            options={
                'verbose_name': 'Blink 수수료 통계',
                'verbose_name_plural': 'Blink 수수료 통계',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expert.directcontractdocument',),
        ),
        migrations.CreateModel(
            name='ExpertUsageStats',
            fields=[
            ],
            options={
                'verbose_name': 'Expert 사용 통계',
                'verbose_name_plural': 'Expert 사용 통계',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expert.directcontractdocument',),
        ),
        migrations.AlterModelOptions(
            name='contractpricingsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='directcontractstagelog',
            options={'ordering': ['started_at'], 'verbose_name': '직접 계약 단계 로그', 'verbose_name_plural': '직접 계약 단계 로그'},
        ),
        migrations.RemoveField(
            model_name='contractpricingsetting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contractpricingsetting',
            name='updated_at',
        ),
    ]
