# Generated by Django 5.2.2 on 2025-11-12 08:48

from django.conf import settings
from django.db import migrations, models


def sync_lightning_ids(apps, schema_editor):
    Document = apps.get_model("expert", "DirectContractDocument")
    qs = Document.objects.all().only("id", "payload", "creator_lightning_id", "counterparty_lightning_id")
    for document in qs.iterator():
        payload = document.payload or {}
        creator_id = payload.get("creator_lightning_id") or ""
        counterparty_id = payload.get("counterparty_lightning_id") or ""
        updated_fields = []
        if creator_id and document.creator_lightning_id != creator_id:
            document.creator_lightning_id = creator_id
            updated_fields.append("creator_lightning_id")
        if counterparty_id and document.counterparty_lightning_id != counterparty_id:
            document.counterparty_lightning_id = counterparty_id
            updated_fields.append("counterparty_lightning_id")
        if updated_fields:
            document.save(update_fields=updated_fields)


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0013_expertblinkrevenuestats_expertusagestats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontractdocument',
            name='counterparty_lightning_id',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='directcontractdocument',
            name='creator_lightning_id',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='directcontractdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='directcontractdocument',
            name='status',
            field=models.CharField(choices=[('pending_counterparty', '상대방 입력 대기'), ('counterparty_in_progress', '상대방 진행 중'), ('completed', '계약 완료')], db_index=True, default='pending_counterparty', max_length=32),
        ),
        migrations.AddIndex(
            model_name='directcontractdocument',
            index=models.Index(fields=['creator', '-created_at'], name='doc_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='directcontractdocument',
            index=models.Index(fields=['counterparty_user', '-created_at'], name='doc_counterparty_created_idx'),
        ),
        migrations.RunPython(sync_lightning_ids, noop),
    ]
