# Generated by Django 5.2.2 on 2025-11-13 11:07

from django.db import migrations
import textwrap


def seed_slides(apps, schema_editor):
    Slide = apps.get_model('expert', 'ExpertHeroSlide')
    if Slide.objects.exists():
        return

    content_html = textwrap.dedent(
        """
        <div class=\"direct-contract-hero section\">
            <div class=\"container hero-grid\">
                <div class=\"hero-copy\">
                    <span class=\"hero-pill\">1:1 직접 계약</span>
                    <h1>의뢰자와 수행자가 바로 합의하고 서명하는 직거래 계약</h1>
                    <p>직접 계약은 의뢰자·수행자 사이의 거래를 지원하며, 정산 정보 입력부터 서명 공유까지 한 화면에서 진행됩니다.</p>
                    <div class=\"hero-actions\">
                        {% if request.user.is_authenticated %}
                            <a class=\"button is-primary is-medium\" href=\"{% url 'expert:direct-draft' %}\">계약 작성 시작</a>
                        {% else %}
                            <a class=\"button is-primary is-medium\" href=\"{% url 'expert:login' %}?next={% url 'expert:direct-draft' %}\">계약 작성 시작</a>
                        {% endif %}
                        <p class=\"is-size-7 has-text-grey\">Expert는 라이트닝 로그인으로만 이용 가능합니다.</p>
                    </div>
                </div>
                <div class=\"hero-side\">
                    <div class=\"hero-card\">
                        <p class=\"hero-card-title\">기본 원칙</p>
                        <ul>
                            <li><span class=\"hero-bullet\">역할 지원</span> 의뢰자/수행자 중 누구나 계약 개설</li>
                            <li><span class=\"hero-bullet\">라이트닝 인증</span> 지갑 서명으로 인증된 계정만 정산 정보 입력/서명 가능</li>
                            <li><span class=\"hero-bullet\">옵션 결제</span> 유료 정책이 켜지면 단계별 사토시 결제 후 진행</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        """
    ).strip()

    background_css = textwrap.dedent(
        """
        background: radial-gradient(circle at top left, rgba(255, 184, 0, 0.35), transparent 45%),
                    radial-gradient(circle at bottom right, rgba(56, 189, 248, 0.25), transparent 50%),
                    linear-gradient(135deg, #0f172a, #111827 55%, #020617 100%);
        """
    ).strip()

    Slide.objects.create(
        name="기본 Hero",
        content_html=content_html,
        background_css=background_css,
        overlay_color="rgba(2, 6, 23, 0.65)",
        rotation_seconds=8,
        order=0,
        is_active=True,
    )


def unseed_slides(apps, schema_editor):
    Slide = apps.get_model('expert', 'ExpertHeroSlide')
    Slide.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_expertheroslide'),
    ]

    operations = [
        migrations.RunPython(seed_slides, unseed_slides),
    ]
