# Generated by Django 5.2.2 on 2025-11-14 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermypagehistory'),
        ('expert', '0016_seed_expert_hero_slides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertPdfPreviewProxy',
            fields=[
            ],
            options={
                'verbose_name': '계약서 PDF 검증',
                'verbose_name_plural': '계약서 PDF 검증',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expert.contracttemplate',),
        ),
        migrations.CreateModel(
            name='ContractIntegrityCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=150, verbose_name='계약명')),
                ('document_slug', models.CharField(db_index=True, max_length=32, verbose_name='계약 슬러그')),
                ('lightning_public_key', models.CharField(blank=True, max_length=80, verbose_name='라이트닝 공개키')),
                ('result', models.CharField(choices=[('match', '해시 일치'), ('mismatch', '해시 불일치'), ('pending', '해시 미저장')], max_length=16, verbose_name='검증 결과')),
                ('stored_hash', models.CharField(blank=True, max_length=64, verbose_name='저장된 해시')),
                ('uploaded_hash', models.CharField(blank=True, max_length=64, verbose_name='업로드 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검증 시각')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_logs', to='expert.directcontractdocument', verbose_name='계약 문서')),
                ('lightning_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_logs', to='accounts.lightninguser', verbose_name='라이트닝 유저')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_logs', to=settings.AUTH_USER_MODEL, verbose_name='검증 사용자')),
            ],
            options={
                'verbose_name': '계약 위변조 검증 로그',
                'verbose_name_plural': '계약 위변조 검증 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_slug', '-created_at'], name='integrity_doc_slug_idx'), models.Index(fields=['result', '-created_at'], name='integrity_result_idx')],
            },
        ),
    ]
