# Generated by Django 5.2.2 on 2025-11-14 04:45

import textwrap

from django.db import migrations


def add_bsl_donation_slide(apps, schema_editor):
    Slide = apps.get_model("expert", "ExpertHeroSlide")
    if Slide.objects.filter(name="BSL 정기 후원 배너").exists():
        return

    content_html = textwrap.dedent(
        """
        <div class="direct-contract-hero direct-contract-hero--clear section">
            <div class="container hero-grid">
                <div class="hero-copy">
                    <span class="hero-pill">BSL 정기 후원</span>
                    <h1>수수료는 BSL 정기 후원!</h1>
                    <p>Expert에서 발생하는 수수료는 전액 BSL 후원합니다.</p>
                    <p>전자계약도 하고 대한민국 비트코인 커뮤니티도 후원하세요.</p>
                    <div class="hero-actions">
                        {% if request.user.is_authenticated %}
                            <a class="button is-primary is-medium" href="{% url 'expert:direct-draft' %}">계약 작성 시작</a>
                        {% else %}
                            <a class="button is-primary is-medium" href="{% url 'expert:login' %}?next={% url 'expert:direct-draft' %}">계약 작성 시작</a>
                        {% endif %}
                        <p class="is-size-7 has-text-grey">Expert 수수료는 매월 한 번에 정산해 BSL 라이트닝 지갑으로 전달합니다.</p>
                    </div>
                </div>
                <div class="hero-side">
                    <div class="hero-card">
                        <p class="hero-card-title">어떻게 후원되나요?</p>
                        <ul>
                            <li><span class="hero-bullet">100% 투명</span> 건당 고정 수수료를 모두 모아 월별 BSL 송금과 영수증을 공개합니다.</li>
                            <li><span class="hero-bullet">라이트닝</span> Expert 계약 결제만 완료해도 자동으로 후원 금액이 쌓입니다.</li>
                            <li><span class="hero-bullet">커뮤니티</span> 대한민국 비트코인 커뮤니티의 모임·콘텐츠·교육 활동을 지원합니다.</li>
                        </ul>
                        <p class="is-size-7 has-text-grey-light mt-4">계약 파트너를 도우면서 동시에 BSL 장기 프로젝트를 후원해 보세요.</p>
                    </div>
                </div>
            </div>
        </div>
        """
    ).strip()

    background_css = textwrap.dedent(
        """
        background: radial-gradient(circle at 15% 20%, rgba(255, 145, 0, 0.45), transparent 55%),
                    radial-gradient(circle at 85% 15%, rgba(56, 189, 248, 0.25), transparent 45%),
                    linear-gradient(145deg, #020617 0%, #0f172a 55%, #1e293b 100%);
        """
    ).strip()

    Slide.objects.create(
        name="BSL 정기 후원 배너",
        content_html=content_html,
        background_css=background_css,
        overlay_color="transparent",
        rotation_seconds=9,
        order=10,
        is_active=True,
    )


def remove_bsl_donation_slide(apps, schema_editor):
    Slide = apps.get_model("expert", "ExpertHeroSlide")
    Slide.objects.filter(name="BSL 정기 후원 배너").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0017_expertpdfpreviewproxy_contractintegritychecklog"),
    ]

    operations = [
        migrations.RunPython(add_bsl_donation_slide, remove_bsl_donation_slide),
    ]
