# Generated by Django 5.2.2 on 2025-11-14 06:10

from django.db import migrations


def remove_bsl_donation_slide(apps, schema_editor):
    Slide = apps.get_model("expert", "ExpertHeroSlide")
    Slide.objects.filter(name="BSL 정기 후원 배너").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0018_bsl_donation_slide"),
    ]

    operations = [
        migrations.RunPython(remove_bsl_donation_slide, migrations.RunPython.noop),
    ]
