# Generated by Django 5.2.2 on 2025-06-16 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='세션 키')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='전체 파일 수')),
                ('uploaded_files', models.PositiveIntegerField(default=0, verbose_name='업로드된 파일 수')),
                ('failed_files', models.PositiveIntegerField(default=0, verbose_name='실패한 파일 수')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('uploading', '업로드중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '업로드 세션',
                'verbose_name_plural': '업로드 세션들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='파일 타입')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='다운로드 횟수')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일들',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='storage_att_content_31de83_idx'), models.Index(fields=['uploaded_at'], name='storage_att_uploade_f70929_idx'), models.Index(fields=['is_deleted'], name='storage_att_is_dele_5441e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='파일 타입')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 일시')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='세션 키')),
                ('expires_at', models.DateTimeField(verbose_name='만료 일시')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '임시 업로드',
                'verbose_name_plural': '임시 업로드들',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_by'], name='storage_tem_uploade_0327f3_idx'), models.Index(fields=['session_key'], name='storage_tem_session_52cd64_idx'), models.Index(fields=['expires_at'], name='storage_tem_expires_349643_idx'), models.Index(fields=['is_used'], name='storage_tem_is_used_b997ef_idx')],
            },
        ),
    ]
