# Generated by Django 5.2.2 on 2025-06-17 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='temporaryupload',
            index=models.Index(fields=['uploaded_at'], name='storage_tem_uploade_bb1e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryupload',
            index=models.Index(fields=['expires_at', 'is_used'], name='storage_tem_expires_313bff_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['session_id'], name='storage_upl_session_a56975_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user'], name='storage_upl_user_id_2ca3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['session_key'], name='storage_upl_session_612a62_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='storage_upl_status_6058f4_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['created_at'], name='storage_upl_created_8d2374_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['updated_at'], name='storage_upl_updated_bd1772_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['completed_at'], name='storage_upl_complet_0e0cdb_idx'),
        ),
    ]
