# Generated by Django 5.2.2 on 2026-01-06 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minihome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='미니홈 접속 라우트 슬러그 (예: myhome)', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='관리용 이름 (선택)', max_length=100)),
                ('draft_sections', models.JSONField(blank=True, default=list, help_text='미리보기용 섹션 구성(JSON)')),
                ('published_sections', models.JSONField(blank=True, default=list, help_text='공개용 섹션 구성(JSON)')),
                ('is_published', models.BooleanField(default=False, help_text='공개 여부')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(blank=True, help_text='미니홈 관리 권한을 가진 사용자', related_name='minihomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '미니홈',
                'verbose_name_plural': '미니홈',
            },
        ),
    ]
