# Generated by Django 5.2.2 on 2026-01-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minihome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minihome',
            name='domain',
            field=models.CharField(blank=True, help_text='연결할 도메인 (비우면 /minihome/<slug>/ 사용)', max_length=255, null=True, unique=True),
        ),
    ]
