# Generated by Django 5.2.2 on 2026-01-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minihome', '0002_minihome_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='minihome',
            name='draft_background_preset',
            field=models.CharField(blank=True, default='noir', help_text='미리보기 배경 프리셋', max_length=50),
        ),
        migrations.AddField(
            model_name='minihome',
            name='published_background_preset',
            field=models.CharField(blank=True, default='noir', help_text='공개 배경 프리셋', max_length=50),
        ),
    ]
