# Generated by Django 5.2.2 on 2025-07-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='강의명')),
                ('description', models.TextField(verbose_name='강의 설명')),
                ('difficulty', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20, verbose_name='난이도')),
                ('duration', models.PositiveIntegerField(verbose_name='강의 시간(분)')),
                ('max_students', models.PositiveIntegerField(verbose_name='최대 수강인원')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '게시됨'), ('closed', '마감')], default='draft', max_length=20, verbose_name='상태')),
                ('start_date', models.DateTimeField(verbose_name='강의 시작일')),
                ('end_date', models.DateTimeField(verbose_name='강의 종료일')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lectures/thumbnails/', verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.category', verbose_name='카테고리')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('status', models.CharField(choices=[('active', '수강중'), ('completed', '수강완료'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='상태')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='수강완료일')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lecture.lecture', verbose_name='강의')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '강의 수강 등록',
                'verbose_name_plural': '강의 수강 등록',
                'unique_together': {('lecture', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='평점')),
                ('comment', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lecture.lecture', verbose_name='강의')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '강의 리뷰',
                'verbose_name_plural': '강의 리뷰',
                'unique_together': {('lecture', 'student')},
            },
        ),
    ]
