# Generated by Django 5.2.2 on 2025-07-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_add_unique_constraint_live_lecture_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
