# Generated by Django 5.2.2 on 2025-09-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_remove_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='livelectureorder',
            index=models.Index(fields=['live_lecture', '-created_at'], name='lecture_liv_live_le_0f102e_idx'),
        ),
    ]
