# Generated by Django 5.2.2 on 2025-10-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_livelectureorder_lecture_liv_live_le_0f102e_idx'),
        ('ln_payment', '0005_paymenttransaction_file_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLectureManualPaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '라이브 강의 수동 저장 결제',
                'verbose_name_plural': '라이브 강의 수동 저장 결제',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.manualpaymenttransaction',),
        ),
        migrations.CreateModel(
            name='LiveLectureOrderItemReservation',
            fields=[
            ],
            options={
                'verbose_name': '라이브 강의 재고 예약',
                'verbose_name_plural': '라이브 강의 재고 예약',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.orderitemreservation',),
        ),
        migrations.CreateModel(
            name='LiveLecturePaymentStageLog',
            fields=[
            ],
            options={
                'verbose_name': '라이브 강의 결제 단계 로그',
                'verbose_name_plural': '라이브 강의 결제 단계 로그',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymentstagelog',),
        ),
        migrations.CreateModel(
            name='LiveLecturePaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '라이브 강의 결제 트랜잭션',
                'verbose_name_plural': '라이브 강의 결제 트랜잭션',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymenttransaction',),
        ),
    ]
