# Generated by Django 5.2.2 on 2025-06-30 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='밋업 일시'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='기본주소'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location_detail_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='우편번호'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_chat_channel',
            field=models.URLField(blank=True, verbose_name='주최자 소통채널'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_contact',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='올바른 연락처 형식이 아닙니다.', regex='^[\\d\\-\\+\\(\\)\\s]+$')], verbose_name='주최자 연락처'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='주최자 이메일'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='특이사항'),
        ),
    ]
