# Generated by Django 5.2.2 on 2025-06-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_meetup_date_time_meetup_location_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100, verbose_name='참가자 이름')),
                ('participant_email', models.EmailField(max_length=254, verbose_name='참가자 이메일')),
                ('participant_phone', models.CharField(blank=True, max_length=20, verbose_name='참가자 연락처')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('confirmed', '참가 확정'), ('cancelled', '참가 취소'), ('completed', '밋업 완료')], default='pending', max_length=20, verbose_name='상태')),
                ('base_price', models.PositiveIntegerField(verbose_name='기본 참가비(satoshi)')),
                ('options_price', models.PositiveIntegerField(default=0, verbose_name='옵션 추가비(satoshi)')),
                ('total_price', models.PositiveIntegerField(verbose_name='총 참가비(satoshi)')),
                ('is_early_bird', models.BooleanField(default=False, verbose_name='조기등록 할인 적용')),
                ('discount_rate', models.PositiveIntegerField(default=0, verbose_name='할인율(%)')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='원래 가격(satoshi)')),
                ('payment_hash', models.CharField(blank=True, max_length=255, verbose_name='결제 해시')),
                ('payment_request', models.TextField(blank=True, verbose_name='결제 요청(인보이스)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 시간')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='참가 확정 시간')),
                ('confirmation_message_sent', models.BooleanField(default=False, verbose_name='확정 안내 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='meetup.meetup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetup_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '밋업 주문',
                'verbose_name_plural': '밋업 주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetupOrderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.IntegerField(verbose_name='추가요금(satoshi)')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupchoice')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='meetup.meetuporder')),
            ],
            options={
                'verbose_name': '밋업 주문 옵션',
                'verbose_name_plural': '밋업 주문 옵션',
            },
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['meetup', 'status'], name='meetup_meet_meetup__1324b3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['user', 'status'], name='meetup_meet_user_id_d7b8de_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['order_number'], name='meetup_meet_order_n_c2be65_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['payment_hash'], name='meetup_meet_payment_bf246c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetuporderoption',
            unique_together={('order', 'option')},
        ),
    ]
