# Generated by Django 5.2.2 on 2025-06-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_meetuporder_meetuporderoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location_tbd',
            field=models.BooleanField(default=False, verbose_name='장소 추후 공지'),
        ),
    ]
