# Generated by Django 5.2.2 on 2025-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_meetup_location_tbd'),
        ('stores', '0023_add_email_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['store'], name='meetup_meet_store_i_730444_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['is_active'], name='meetup_meet_is_acti_594e02_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['date_time'], name='meetup_meet_date_ti_120b75_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['store', 'is_active'], name='meetup_meet_store_i_321e71_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['store', 'date_time'], name='meetup_meet_store_i_253a33_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['deleted_at'], name='meetup_meet_deleted_ffb32b_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['store', 'deleted_at'], name='meetup_meet_store_i_ac1cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['created_at'], name='meetup_meet_created_b38b77_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['updated_at'], name='meetup_meet_updated_3950d9_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['is_temporarily_closed'], name='meetup_meet_is_temp_f32a18_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupchoice',
            index=models.Index(fields=['option'], name='meetup_meet_option__450c79_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupchoice',
            index=models.Index(fields=['order'], name='meetup_meet_order_6a3ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupchoice',
            index=models.Index(fields=['option', 'order'], name='meetup_meet_option__8d4543_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupchoice',
            index=models.Index(fields=['additional_price'], name='meetup_meet_additio_75b5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupchoice',
            index=models.Index(fields=['created_at'], name='meetup_meet_created_d4b51a_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupoption',
            index=models.Index(fields=['meetup'], name='meetup_meet_meetup__99fe72_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupoption',
            index=models.Index(fields=['order'], name='meetup_meet_order_094f32_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupoption',
            index=models.Index(fields=['meetup', 'order'], name='meetup_meet_meetup__252d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupoption',
            index=models.Index(fields=['is_required'], name='meetup_meet_is_requ_cc663f_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupoption',
            index=models.Index(fields=['created_at'], name='meetup_meet_created_80edf8_idx'),
        ),
    ]
