# Generated by Django 5.2.2 on 2025-07-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_meetup_meetup_meet_store_i_730444_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuporder',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='참석 여부'),
        ),
        migrations.AddField(
            model_name='meetuporder',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='참석 체크 시간'),
        ),
    ]
