# Generated by Django 5.2.2 on 2025-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_meetuporder_auto_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='무료 밋업'),
        ),
    ]
