# Generated by Django 5.2.2 on 2025-07-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_meetup_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrderManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '🔍 Pending 주문 관리',
                'verbose_name_plural': '🔍 Pending 주문 관리',
                'managed': False,
            },
        ),
    ]
