# Generated by Django 5.2.2 on 2025-01-15 12:00

from django.db import migrations
import re


def update_meetup_order_number_format(apps, schema_editor):
    """기존 밋업 주문번호를 새로운 형식으로 업데이트"""
    MeetupOrder = apps.get_model('meetup', 'MeetupOrder')
    
    # UUID 형태의 기존 주문번호 패턴을 찾아서 업데이트
    orders = MeetupOrder.objects.all().order_by('created_at')
    
    for order in orders:
        order_number = order.order_number
        
        # 기존 패턴: TICKET-20241215-A1B2C3D4 (UUID 형태)
        # 새 패턴: TICKET-20241215-143020 (시분초 형태)
        
        # 이미 시분초 형태인 경우 건너뛰기 (6자리 숫자)
        if re.match(r'^TICKET-\d{8}-\d{6}$', order_number):
            continue
            
        # TICKET-8자리숫자-UUID 패턴 매칭
        match = re.match(r'^TICKET-(\d{8})-[A-Z0-9]{8}$', order_number)
        if match:
            date_part = match.group(1)  # 20241215
            
            # 생성 시간을 사용하여 시분초 생성
            created_at = order.created_at
            time_part = created_at.strftime('%H%M%S')  # 143020
            
            # 새로운 형식으로 변경
            new_order_number = f"TICKET-{date_part}-{time_part}"
            
            # 중복 확인 및 처리
            counter = 0
            original_new_order_number = new_order_number
            
            while MeetupOrder.objects.filter(order_number=new_order_number).exists():
                counter += 1
                # 중복이 있으면 뒤에 카운터 추가
                new_order_number = f"{original_new_order_number}-{counter:02d}"
            
            # 주문번호 업데이트
            order.order_number = new_order_number
            order.save(update_fields=['order_number'])
            
            print(f"Updated: {order_number} -> {new_order_number}")


def reverse_meetup_order_number_format(apps, schema_editor):
    """마이그레이션 롤백 시 실행될 함수 (실제로는 되돌릴 수 없음)"""
    # UUID를 다시 생성하는 것은 불가능하므로 경고 메시지만 출력
    print("WARNING: 밋업 주문번호 형식 변경은 되돌릴 수 없습니다.")
    print("UUID 정보가 손실되어 원래 형태로 복원할 수 없습니다.")


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_pendingordermanager'),
    ]

    operations = [
        migrations.RunPython(
            update_meetup_order_number_format,
            reverse_meetup_order_number_format,
        ),
    ] 