# Generated by Django 5.2.2 on 2025-07-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_pendingordermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingOrderManager',
        ),
    ]
