# Generated by Django 5.2.2 on 2025-07-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_meetupparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupParticipantEntry',
            fields=[
            ],
            options={
                'verbose_name': '밋업 참가자 항목',
                'verbose_name_plural': '밋업 참가자 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meetup.meetuporder',),
        ),
    ]
