# Generated by Django 5.2.2 on 2025-07-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_update_meetup_order_number_format'),
        ('meetup', '0012_meetupparticipantentry'),
    ]

    operations = [
    ]
