# Generated by Django migration for meetup order number format update

from django.db import migrations
import uuid


def update_meetup_order_number_format(apps, schema_editor):
    """기존 밋업 주문번호를 새로운 형식으로 업데이트: store_id-ticket-YYMM-해시값"""
    MeetupOrder = apps.get_model('meetup', 'MeetupOrder')
    
    # 모든 밋업 주문을 가져와서 생성일시 순으로 정렬
    meetup_orders = MeetupOrder.objects.select_related('meetup__store').all().order_by('created_at')
    
    updated_count = 0
    for order in meetup_orders:
        try:
            # 새로운 주문번호 생성
            created_at = order.created_at
            store_id = order.meetup.store.store_id
            year_month = created_at.strftime('%y%m')  # 2501 형식
            hash_value = str(uuid.uuid4())[:8].upper()
            
            new_order_number = f"{store_id}-ticket-{year_month}-{hash_value}"
            
            # 중복 확인 및 처리
            counter = 0
            
            while MeetupOrder.objects.filter(order_number=new_order_number).exists():
                counter += 1
                # 중복이 있으면 새로운 해시값 생성
                hash_value = str(uuid.uuid4())[:8].upper()
                new_order_number = f"{store_id}-ticket-{year_month}-{hash_value}"
                
                # 무한루프 방지
                if counter > 100:
                    break
            
            # 주문번호 업데이트
            old_order_number = order.order_number
            order.order_number = new_order_number
            order.save(update_fields=['order_number'])
            
            updated_count += 1
            print(f"Updated MeetupOrder {order.id}: {old_order_number} -> {new_order_number}")
            
        except Exception as e:
            print(f"Error updating MeetupOrder {order.id}: {str(e)}")
            continue
    
    print(f"Total updated meetup orders: {updated_count}")


def reverse_meetup_order_number_format(apps, schema_editor):
    """역마이그레이션은 지원하지 않음 (데이터 손실 위험)"""
    print("Warning: 밋업 주문번호 형식 변경의 역마이그레이션은 지원하지 않습니다.")
    print("기존 주문번호 정보가 손실될 수 있습니다.")


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0013_merge_20250707_0833'),
    ]

    operations = [
        migrations.RunPython(
            update_meetup_order_number_format,
            reverse_meetup_order_number_format,
        ),
    ] 