# Generated by Django 5.2.2 on 2025-09-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_update_order_number_format_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['meetup', '-created_at'], name='meetup_meet_meetup__276e50_idx'),
        ),
    ]
