# Generated by Django 5.2.2 on 2025-09-25 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0016_meetuporder_meetup_meet_meetup__276e50_idx'),
        ('stores', '0026_store_stores_stor_email_e_ff14a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['is_free'], name='meetup_meet_is_free_ed72b4_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['is_discounted'], name='meetup_meet_is_disc_c6e20b_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['meetup', 'status', '-created_at'], name='meetup_order_status_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['attended', '-created_at'], name='meetup_order_att_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuporder',
            index=models.Index(fields=['is_early_bird'], name='meetup_meet_is_earl_5dce72_idx'),
        ),
    ]
