# Generated by Django 5.2.2 on 2025-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='SatoShop', help_text='브라우저 탭에 표시되는 사이트 제목', max_length=100, verbose_name='사이트 제목')),
                ('site_description', models.TextField(default='비트코인 라이트닝 결제 플랫폼', help_text='메타 태그에 사용되는 사이트 설명', verbose_name='사이트 설명')),
                ('hero_title', models.CharField(default='누구나 쉽게 만드는 비트코인 온라인 스토어', max_length=200, verbose_name='히어로 제목')),
                ('hero_subtitle', models.TextField(default='복잡한 설정 없이 5분만에 온라인 스토어를 만들고 비트코인으로 결제받으세요', verbose_name='히어로 부제목')),
                ('youtube_video_id', models.CharField(default='dd2RzyPu4ok', help_text='유튜브 URL에서 v= 뒤의 ID만 입력하세요 (예: dd2RzyPu4ok)', max_length=20, verbose_name='유튜브 비디오 ID')),
                ('youtube_autoplay', models.BooleanField(default=True, help_text='페이지 로드 시 비디오 자동 재생', verbose_name='자동 재생')),
                ('youtube_mute', models.BooleanField(default=True, help_text='비디오 음소거 상태로 재생', verbose_name='음소거')),
                ('youtube_loop', models.BooleanField(default=True, help_text='비디오 반복 재생', verbose_name='반복 재생')),
                ('youtube_controls', models.BooleanField(default=False, help_text='비디오 재생 컨트롤 표시', verbose_name='컨트롤 표시')),
                ('contact_email', models.EmailField(blank=True, help_text='고객 문의용 이메일 주소', max_length=254, verbose_name='연락처 이메일')),
                ('github_url', models.URLField(blank=True, help_text='GitHub 프로젝트 링크', verbose_name='GitHub URL')),
                ('enable_user_registration', models.BooleanField(default=True, help_text='새로운 사용자 회원가입 허용', verbose_name='회원가입 허용')),
                ('enable_store_creation', models.BooleanField(default=True, help_text='사용자의 새 스토어 생성 허용', verbose_name='스토어 생성 허용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
