# Generated by Django 5.2.2 on 2025-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_krw_rate', models.DecimalField(decimal_places=2, help_text='1 BTC = ? KRW', max_digits=15, verbose_name='BTC/KRW 환율')),
                ('api_response_data', models.JSONField(help_text='업비트 API 전체 응답 데이터', verbose_name='API 응답 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '환율 데이터',
                'verbose_name_plural': '환율 데이터',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='exchange_rate_update_interval',
            field=models.PositiveIntegerField(default=10, help_text='업비트 API에서 환율을 가져오는 간격 (분 단위)', verbose_name='환율 업데이트 간격 (분)'),
        ),
    ]
