# Generated by Django 5.2.2 on 2025-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_exchangerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_address',
            field=models.CharField(blank=True, help_text='회사 주소 (선택사항)', max_length=300, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_business_hours',
            field=models.CharField(default='24시간 온라인 서비스', help_text='서비스 운영시간 안내', max_length=100, verbose_name='운영시간'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_company_name',
            field=models.CharField(default='SatoShop', help_text='푸터에 표시될 회사명 또는 서비스명', max_length=100, verbose_name='회사명/서비스명'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2024 SatoShop. All rights reserved.', help_text='푸터 하단에 표시될 저작권 문구', max_length=200, verbose_name='저작권 표시'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='비트코인 라이트닝으로 누구나 쉽게 사용하는 온라인 스토어 플랫폼', help_text='푸터에 표시될 간단한 서비스 설명', verbose_name='푸터 설명'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_discord_url',
            field=models.URLField(blank=True, help_text='디스코드 서버 링크', verbose_name='디스코드 URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_phone',
            field=models.CharField(blank=True, help_text='고객 문의 전화번호 (선택사항)', max_length=20, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_telegram_url',
            field=models.URLField(blank=True, help_text='텔레그램 채널/그룹 링크', verbose_name='텔레그램 URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_twitter_url',
            field=models.URLField(blank=True, help_text='트위터 프로필 링크', verbose_name='트위터 URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default='코딩 없이 5분 만에 스토어 구축 • 즉석 비트코인 결제 • 전세계 고객 접근', help_text='히어로 섹션 하단에 표시될 추가 설명', verbose_name='히어로 설명'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_button_text',
            field=models.CharField(default='지금 시작하기', help_text='히어로 섹션의 주요 액션 버튼 텍스트', max_length=50, verbose_name='주요 버튼 텍스트'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_button_text',
            field=models.CharField(default='스토어 둘러보기', help_text='히어로 섹션의 보조 액션 버튼 텍스트', max_length=50, verbose_name='보조 버튼 텍스트'),
        ),
    ]
