# Generated by Django 5.2.2 on 2025-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_sitesettings_footer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_site_header',
            field=models.CharField(default='SatoShop 관리자', help_text='Django 관리자 페이지 상단에 표시되는 제목', max_length=100, verbose_name='관리자 사이트 제목'),
        ),
    ]
