# Generated by Django 5.2.2 on 2025-06-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_sitesettings_admin_site_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics 추적 ID (예: G-XXXXXXXXXX 또는 UA-XXXXXXXXX-X)', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_default_image',
            field=models.URLField(blank=True, help_text='링크 공유 시 표시될 기본 이미지 URL (1200x630 권장)', verbose_name='기본 Open Graph 이미지'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_site_name',
            field=models.CharField(default='SatoShop', help_text='소셜 미디어에서 표시될 사이트명', max_length=100, verbose_name='Open Graph 사이트명'),
        ),
    ]
