# Generated by Django 5.2.2 on 2025-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO용 메타 키워드 (쉼표로 구분, 예: 비트코인, 라이트닝, 온라인스토어, 암호화폐)', verbose_name='메타 키워드'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(default='비트코인 라이트닝 결제 플랫폼', help_text='메타 태그에 사용되는 사이트 설명 (최대 200자)', max_length=200, verbose_name='사이트 설명'),
        ),
    ]
