# Generated by Django 5.2.2 on 2025-06-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_remove_apscheduler_tables'),
        ('myshop', '0006_sitesettings_meta_keywords_and_more'),
    ]

    operations = [
    ]
