# Generated by Django 5.2.2 on 2025-06-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_merge_20250616_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='사이트 파비콘 이미지 URL (16x16, 32x32 권장, PNG 형식)', verbose_name='파비콘 URL'),
        ),
    ]
