# Generated by Django 5.2.2 on 2025-06-16 23:48

import myshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_sitesettings_favicon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default=myshop.models.get_current_year_copyright, help_text='푸터 하단에 표시될 저작권 문구 (자동으로 현재 연도가 설정됩니다)', max_length=200, verbose_name='저작권 표시'),
        ),
    ]
