# Generated by Django 5.2.2 on 2025-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_alter_sitesettings_footer_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.CharField(blank=True, help_text='사이트 파비콘 이미지 경로 (16x16, 32x32 권장, PNG 형식, 예: /static/images/favicon.png 또는 https://example.com/favicon.png)', max_length=500, verbose_name='파비콘 경로'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_default_image',
            field=models.CharField(blank=True, help_text='링크 공유 시 표시될 기본 이미지 경로 (1200x630 권장, 예: /static/images/og-image.png 또는 https://example.com/image.png)', max_length=500, verbose_name='기본 Open Graph 이미지'),
        ),
    ]
