# Generated by Django 5.2.2 on 2025-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_sitesettings_myshop_site_created_a71e4b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blink_api_doc_url',
            field=models.URLField(default='#', help_text='스토어 생성 시 블링크 API 정보 얻는 방법 문서 링크', verbose_name='블링크 API 문서 링크'),
        ),
    ]
