# Generated by Django 5.2.2 on 2025-06-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_sitesettings_blink_api_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_logo_url',
            field=models.CharField(blank=True, help_text='Django 관리자 페이지에 표시될 로고 이미지 경로 (예: /static/images/logo.png 또는 https://example.com/logo.png). 비어있으면 사이트 제목이 텍스트로 표시됩니다.', max_length=500, verbose_name='관리자 로고 이미지 경로'),
        ),
    ]
