# Generated by Django 5.2.2 on 2025-06-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_sitesettings_admin_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='admin_logo_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_url',
            field=models.CharField(blank=True, help_text="메인 사이트에 표시될 로고 이미지 경로 (예: /static/images/logo.png 또는 https://example.com/logo.png). 비어있으면 'SatoShop' 텍스트로 표시됩니다.", max_length=500, verbose_name='사이트 로고 이미지 경로'),
        ),
    ]
