# Generated by Django 5.2.2 on 2025-06-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_remove_sitesettings_admin_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', '이용약관'), ('privacy', '개인정보처리방침'), ('refund', '환불 및 반품 정책')], help_text='관리할 문서의 유형을 선택하세요', max_length=20, unique=True, verbose_name='문서 유형')),
                ('title', models.CharField(help_text='사이트에 표시될 문서 제목', max_length=100, verbose_name='문서 제목')),
                ('content', models.TextField(help_text='마크다운 형식으로 작성하세요. HTML 태그도 사용 가능합니다.', verbose_name='문서 내용')),
                ('is_active', models.BooleanField(default=True, help_text='체크 해제 시 사이트에서 숨겨집니다', verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문서 관리',
                'verbose_name_plural': '문서 관리',
                'ordering': ['document_type'],
                'indexes': [models.Index(fields=['document_type'], name='myshop_docu_documen_ee05c3_idx'), models.Index(fields=['is_active'], name='myshop_docu_is_acti_3e1e76_idx')],
            },
        ),
    ]
