# Generated by Django 5.2.2 on 2025-06-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_documentcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='exchange_rate_update_interval',
        ),
    ]
