# Generated by Django 5.2.2 on 2025-06-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_remove_exchange_rate_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='exchange_rate_notification_email',
            field=models.EmailField(default='satoshopkr@gmail.com', help_text='환율 데이터 업데이트 시 알림을 받을 이메일 주소', max_length=254, verbose_name='환율 알림 이메일'),
        ),
    ]
