# Generated by Django 5.2.2 on 2025-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0017_add_exchange_rate_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_help_url',
            field=models.URLField(blank=True, help_text='스토어 이메일 설정 시 사용자에게 제공되는 Gmail 앱 비밀번호 설정 도움말 링크', verbose_name='Gmail 앱 비밀번호 도움말 URL'),
        ),
    ]
