# Generated by Django 5.2.2 on 2025-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0018_add_gmail_help_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='exchange_rate_notification_email',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_telegram_exchange_rate_alerts',
            field=models.BooleanField(default=True, help_text='환율 데이터가 업데이트될 때마다 텔레그램으로 즉시 알림 전송', verbose_name='텔레그램 환율 즉시 알림'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='환율 알림을 보낼 텔레그램 봇의 API 토큰 (BotFather에서 생성)', max_length=500, verbose_name='텔레그램 봇 토큰'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='알림을 받을 텔레그램 채팅 ID (개인 또는 그룹 채팅)', max_length=100, verbose_name='텔레그램 채팅 ID'),
        ),
    ]
