# Generated by Django 5.2.2 on 2025-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0019_replace_email_with_telegram_for_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='btc_usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='1 BTC = ? USD', max_digits=15, null=True, verbose_name='BTC/USD 가격'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='usd_krw_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='1 USD = ? KRW', max_digits=10, null=True, verbose_name='USD/KRW 환율'),
        ),
    ]
