# Generated by Django 5.2.2 on 2025-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_add_usd_fields_to_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meetup_countdown_seconds',
            field=models.PositiveIntegerField(default=180, help_text='밋업 신청 과정에서 각 단계별 제한시간 (초 단위, 기본값 180초)', verbose_name='밋업 신청 카운트다운 시간(초)'),
        ),
    ]
