# Generated by Django 5.2.2 on 2025-07-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0021_sitesettings_meetup_countdown_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='excluded_active_store_ids',
            field=models.TextField(blank=True, help_text='주문이 활발한 스토어 목록에서 제외할 스토어 ID들을 쉼표로 구분하여 입력하세요 (예: demo,test,sample)', verbose_name='주문 활발한 스토어에서 제외할 스토어 ID'),
        ),
    ]
