# Generated by Django 5.2.2 on 2025-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0022_sitesettings_excluded_active_store_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '캐시 관리',
                'verbose_name_plural': '캐시 관리',
                'managed': False,
            },
        ),
    ]
