# Generated by Django 5.2.2 on 2025-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0023_cachemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_address',
            field=models.CharField(blank=True, help_text='수퍼어드민 테스트 주문 시 사용할 기본 주소', max_length=200, verbose_name='수퍼어드민 기본 주소'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_buyer_email',
            field=models.EmailField(blank=True, help_text='수퍼어드민 테스트 주문 시 기본값으로 사용할 이메일 주소', max_length=254, verbose_name='수퍼어드민 기본 이메일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_buyer_name',
            field=models.CharField(blank=True, help_text='수퍼어드민이 테스트 주문을 진행할 때 기본값으로 사용할 주문자 이름', max_length=100, verbose_name='수퍼어드민 기본 주문자 이름'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_buyer_phone',
            field=models.CharField(blank=True, help_text='수퍼어드민 테스트 주문 시 기본값으로 사용할 연락처', max_length=30, verbose_name='수퍼어드민 기본 연락처'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_detail_address',
            field=models.CharField(blank=True, help_text='수퍼어드민 테스트 주문 시 사용할 상세 주소', max_length=200, verbose_name='수퍼어드민 기본 상세주소'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_memo',
            field=models.TextField(blank=True, help_text='수퍼어드민 테스트 주문 시 사용할 기본 배송 요청사항', verbose_name='수퍼어드민 기본 배송 요청사항'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superuser_checkout_postal_code',
            field=models.CharField(blank=True, help_text='수퍼어드민 테스트 주문 시 사용할 기본 우편번호', max_length=10, verbose_name='수퍼어드민 기본 우편번호'),
        ),
    ]
