# Generated by Django 5.2.2 on 2025-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0025_sitesettings_expert_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='슬라이드 이름')),
                ('content_html', models.TextField(help_text='Django 템플릿 문법과 HTML을 함께 사용할 수 있습니다.', verbose_name='콘텐츠 HTML')),
                ('background_css', models.TextField(blank=True, help_text='background, gradient 등 CSS 선언 전체를 입력하세요.', verbose_name='배경 CSS')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/backgrounds/', verbose_name='배경 이미지')),
                ('overlay_color', models.CharField(blank=True, help_text='rgba(2, 6, 23, 0.65) 와 같은 형식을 권장합니다.', max_length=120, verbose_name='오버레이 색상')),
                ('rotation_seconds', models.PositiveIntegerField(default=6, verbose_name='자동 전환 간격(초)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '히어로 캐러셀 슬라이드',
                'verbose_name_plural': '히어로 캐러셀 슬라이드',
                'ordering': ['order', '-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='hero_slide_active_order')],
            },
        ),
    ]
