# Generated by Django 5.2.2 on 2025-11-13 10:51

from django.db import migrations
import textwrap


def seed_carousel(apps, schema_editor):
    Slide = apps.get_model('myshop', 'HeroCarouselSlide')
    SiteSettings = apps.get_model('myshop', 'SiteSettings')

    if Slide.objects.exists():
        return

    site_settings = SiteSettings.objects.first()
    default_title = (
        site_settings.hero_title
        if site_settings and site_settings.hero_title
        else "비트코인 라이트닝으로 만드는 차세대 스토어"
    )
    default_description = (
        site_settings.hero_description
        if site_settings and site_settings.hero_description
        else "누구나 5분 만에 온라인 스토어를 열고 전세계 고객에게 즉시 결제받을 수 있습니다."
    )
    primary_cta = (
        site_settings.hero_primary_button_text
        if site_settings and site_settings.hero_primary_button_text
        else "지금 무료로 시작하기"
    )
    secondary_cta = (
        site_settings.hero_secondary_button_text
        if site_settings and site_settings.hero_secondary_button_text
        else "라이브 스토어 둘러보기"
    )

    content_html = textwrap.dedent(
        f"""
        {{% load humanize %}}
        <div class=\"relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32\">
          <div class=\"grid gap-12 lg:grid-cols-[1.1fr_0.9fr] items-center\">
            <div>
              <span class=\"inline-flex items-center px-4 py-2 rounded-full bg-white/15 text-sm font-medium uppercase tracking-wide backdrop-blur\">
                ⚡ Lightning-Powered Commerce
              </span>
              <h1 class=\"mt-6 text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight\">
                {{% if site_settings and site_settings.hero_title %}}
                  {{{{ site_settings.hero_title|linebreaksbr }}}}
                {{% else %}}
                  {default_title}
                {{% endif %}}
              </h1>
              <p class=\"mt-6 text-lg sm:text-xl text-white/80 max-w-2xl\">
                {{% if site_settings and site_settings.hero_description %}}
                  {{{{ site_settings.hero_description }}}}
                {{% else %}}
                  {default_description}
                {{% endif %}}
              </p>
              <div class=\"mt-10 flex flex-col sm:flex-row gap-4\">
                {{% if user.is_authenticated %}}
                  {{% if not user_has_active_store %}}
                    <a class=\"inline-flex items-center justify-center gap-3 px-8 py-4 rounded-xl bg-white text-gray-900 font-semibold shadow-lg shadow-white/10 hover:shadow-white/20 transition\" href=\"{{% url 'stores:create_store' %}}\">
                      <i class=\"fas fa-plus text-bitcoin\"></i>
                      내 스토어 개설하기
                    </a>
                  {{% else %}}
                    <a class=\"inline-flex items-center justify-center gap-3 px-8 py-4 rounded-xl bg-white text-gray-900 font-semibold shadow-lg shadow-white/10 hover:shadow-white/20 transition\" href=\"{{% url 'stores:store_detail' store_id=user_active_store.store_id %}}\">
                      <i class=\"fas fa-store\"></i>
                      내 스토어 관리하기
                    </a>
                  {{% endif %}}
                {{% else %}}
                  <a class=\"inline-flex items-center justify-center gap-3 px-8 py-4 rounded-xl bg-white text-gray-900 font-semibold shadow-lg shadow-white/10 hover:shadow-white/20 transition\" href=\"{{% url 'accounts:signup' %}}\">
                    <i class=\"fas fa-rocket text-bitcoin\"></i>
                    {{% if site_settings and site_settings.hero_primary_button_text %}}
                      {{{{ site_settings.hero_primary_button_text }}}}
                    {{% else %}}
                      {primary_cta}
                    {{% endif %}}
                  </a>
                {{% endif %}}
                <a class=\"inline-flex items-center justify-center gap-3 px-8 py-4 rounded-xl border border-white/60 text-white font-semibold hover:bg-white/10 transition\" href=\"{{% url 'stores:browse_stores' %}}\">
                  <i class=\"fas fa-compass\"></i>
                  {{% if site_settings and site_settings.hero_secondary_button_text %}}
                    {{{{ site_settings.hero_secondary_button_text }}}}
                  {{% else %}}
                    {secondary_cta}
                  {{% endif %}}
                </a>
              </div>
              <dl class=\"mt-12 grid grid-cols-2 gap-6 max-w-lg text-left\">
                <div class=\"stat-card\">
                  <dt class=\"text-sm font-medium text-white/70\">구축 소요 시간</dt>
                  <dd class=\"mt-1 text-3xl font-bold\">5분</dd>
                  <p class=\"mt-2 text-sm text-white/70\">템플릿 선택 후 즉시 결제 연동</p>
                </div>
                <div class=\"stat-card\">
                  <dt class=\"text-sm font-medium text-white/70\">라이트닝 결제 성공률</dt>
                  <dd class=\"mt-1 text-3xl font-bold\">99.9%</dd>
                  <p class=\"mt-2 text-sm text-white/70\">Blink 기반 실시간 검증</p>
                </div>
              </dl>
            </div>
            <div class=\"relative\">
              <div class=\"relative rounded-3xl bg-white/10 backdrop-blur-sm border border-white/10 shadow-2xl p-6 sm:p-8\">
                <div class=\"flex items-center gap-3 text-sm font-semibold text-white/80\">
                  <span class=\"px-3 py-1 rounded-full bg-white/10\">Live Dashboard</span>
                  <span class=\"px-3 py-1 rounded-full bg-white/10\">Lightning Ready</span>
                </div>
                <div class=\"mt-6 space-y-4 text-sm text-white/80\">
                  <div class=\"demo-card\">
                    <div class=\"flex items-start justify-between gap-4\">
                      <div>
                        <p class=\"text-xs uppercase tracking-wide text-white/60\">스토어 현황</p>
                        <p class=\"mt-1 text-2xl font-semibold\">
                          {{{{ home_metrics.total_stores|default_if_none:0|intcomma }}}}개
                        </p>
                      </div>
                      <span class=\"badge-success\">
                        활성 {{{{ home_metrics.active_stores|default_if_none:0|intcomma }}}}개
                      </span>
                    </div>
                    <p class=\"mt-3 text-xs text-white/70\">
                      시스템 어드민 기준 운영 중인 스토어 수치를 실시간 반영합니다.
                    </p>
                  </div>
                  <div class=\"demo-card\">
                    <div class=\"flex items-start justify-between gap-4\">
                      <div>
                        <p class=\"text-xs uppercase tracking-wide text-white/60\">등록된 아이템</p>
                        <p class=\"mt-1 text-2xl font-semibold\">
                          {{{{ home_metrics.items.total|default_if_none:0|intcomma }}}}개
                        </p>
                      </div>
                      <span class=\"badge-neutral\">총합</span>
                    </div>
                    <div class=\"mt-3 text-xs text-white/70 flex flex-wrap gap-x-4 gap-y-1\">
                      <span>상품 {{{{ home_metrics.items.products|default_if_none:0|intcomma }}}}개</span>
                      <span>밋업 {{{{ home_metrics.items.meetups|default_if_none:0|intcomma }}}}개</span>
                      <span>파일 {{{{ home_metrics.items.digital_files|default_if_none:0|intcomma }}}}개</span>
                      <span>라이브강의 {{{{ home_metrics.items.live_lectures|default_if_none:0|intcomma }}}}개</span>
                      <span>메뉴 {{{{ home_metrics.items.menus|default_if_none:0|intcomma }}}}개</span>
                    </div>
                  </div>
                  <div class=\"demo-card\">
                    {{% if home_metrics.exchange_rate %}}
                    <div class=\"flex items-start justify-between gap-4\">
                      <div>
                        <p class=\"text-xs uppercase tracking-wide text-white/60\">BTC/KRW 환율</p>
                        <p class=\"mt-1 text-2xl font-semibold\">
                          1 BTC = {{{{ home_metrics.exchange_rate.btc_krw_rate|floatformat:0|intcomma }}}}원
                        </p>
                      </div>
                      <span class=\"badge-neutral\">업비트</span>
                    </div>
                    <p class=\"mt-2 text-xs text-white/70\">
                      업데이트: {{{{ home_metrics.exchange_rate.updated_at|date:'m/d H:i' }}}}
                    </p>
                    {{% else %}}
                    <p class=\"text-white/70 text-sm\">환율 데이터를 불러오는 중입니다…</p>
                    {{% endif %}}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        """
    ).strip()

    background_css = textwrap.dedent(
        """
        background: radial-gradient(circle at top left, rgba(255, 184, 0, 0.35), transparent 45%),
                    radial-gradient(circle at bottom right, rgba(56, 189, 248, 0.25), transparent 50%),
                    linear-gradient(135deg, #0f172a, #111827 55%, #020617 100%);
        """
    ).strip()

    Slide.objects.create(
        name="기본 소개",
        content_html=content_html,
        background_css=background_css,
        overlay_color="rgba(2, 6, 23, 0.65)",
        order=0,
        rotation_seconds=7,
        is_active=True,
    )


def unseed_carousel(apps, schema_editor):
    Slide = apps.get_model('myshop', 'HeroCarouselSlide')
    Slide.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0026_herocarouselslide'),
    ]

    operations = [
        migrations.RunPython(seed_carousel, unseed_carousel),
    ]
