# Generated by Django 5.2.2 on 2025-11-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0027_seed_hero_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroCarouselSlide',
        ),
    ]
