# Generated by Django 5.2.2 on 2025-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0028_delete_herocarouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_expert_pdf_preview_tool',
            field=models.BooleanField(default=False, help_text='장고 어드민에서 계약서 PDF 미리보기 도구를 사용할 수 있도록 허용합니다.', verbose_name='Expert PDF 검증 도구'),
        ),
    ]
