# Generated by Django 5.2.2 on 2025-12-12 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='키 용도/대상 메모', max_length=100)),
                ('key_prefix', models.CharField(db_index=True, help_text='키 앞 16자. 원문 키는 저장하지 않음.', max_length=16)),
                ('key_hash', models.CharField(help_text='SHA256 해시. 원문 키는 저장하지 않음.', max_length=128, unique=True)),
                ('scopes', models.CharField(default='stores:read', help_text='허용 스코프(콤마 구분). 기본은 stores:read', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='비활성화 시 403 반환')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API 키',
                'verbose_name_plural': 'API 키',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_prefix'], name='api_apikey_key_pre_00b949_idx'), models.Index(fields=['is_active'], name='api_apikey_is_acti_ee92d2_idx'), models.Index(fields=['created_at'], name='api_apikey_created_17352f_idx')],
            },
        ),
    ]
