# Generated by Django 5.2.2 on 2025-12-12 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='설명용 이름', max_length=100)),
                ('origin', models.CharField(help_text='스킴 포함 Origin (예: https://example.com:8443)', max_length=200, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API 허용 Origin',
                'verbose_name_plural': 'API 허용 Origin',
                'ordering': ['origin'],
                'indexes': [models.Index(fields=['origin'], name='api_apiallo_origin_dfd6b5_idx'), models.Index(fields=['is_active'], name='api_apiallo_is_acti_09b55b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiIpAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='설명용 이름', max_length=100)),
                ('cidr', models.CharField(help_text='IPv4/IPv6 주소 또는 CIDR (예: 203.0.113.0/24)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API IP 허용 목록',
                'verbose_name_plural': 'API IP 허용 목록',
                'ordering': ['cidr'],
                'indexes': [models.Index(fields=['cidr'], name='api_apiipal_cidr_31989c_idx'), models.Index(fields=['is_active'], name='api_apiipal_is_acti_4a2043_idx')],
            },
        ),
    ]
