# Generated by Django 5.2.2 on 2025-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiallowedorigin_apiipallowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='channel_slug',
            field=models.SlugField(blank=True, help_text='채널 구분 슬러그(예: partner-a, ios-app). 주문/집계용'),
        ),
    ]
