# Generated by Django 5.2.2 on 2026-02-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apikey_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='auth_method',
            field=models.CharField(choices=[('api_key', '기존 API 키(Bearer)'), ('nostr', 'Nostr 공개키 서명')], db_index=True, default='api_key', help_text='인증 방식 선택. Nostr 선택 시 Bearer 키 대신 Nostr 서명 검증 사용', max_length=20),
        ),
        migrations.AddField(
            model_name='apikey',
            name='nostr_pubkey',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nostr 인증용 공개키(32바이트 hex). auth_method=nostr 일 때 필수', max_length=64),
        ),
    ]
