# Generated by Django 5.2.4 on 2025-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('score', models.IntegerField(verbose_name='점수')),
                ('wave', models.IntegerField(default=0, verbose_name='웨이브')),
                ('weapon_level', models.IntegerField(default=0, verbose_name='무기 레벨')),
                ('play_time', models.IntegerField(default=0, verbose_name='플레이 시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '랭킹',
                'verbose_name_plural': '랭킹 목록',
                'ordering': ['-score', '-wave', 'created_at'],
            },
        ),
    ]
