# Generated by Django 5.2.4 on 2025-07-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('started_at', models.DateTimeField(verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('final_score', models.IntegerField(default=0, verbose_name='최종 점수')),
                ('final_wave', models.IntegerField(default=1, verbose_name='최종 웨이브')),
                ('final_weapon_level', models.IntegerField(default=1, verbose_name='최종 무기 레벨')),
                ('play_duration', models.IntegerField(default=0, verbose_name='플레이 시간(초)')),
                ('enemies_killed', models.IntegerField(default=0, verbose_name='처치한 적 수')),
                ('boss_killed', models.IntegerField(default=0, verbose_name='처치한 보스 수')),
                ('items_collected', models.IntegerField(default=0, verbose_name='획득한 아이템 수')),
                ('is_completed', models.BooleanField(default=False, verbose_name='정상 종료')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
            ],
            options={
                'verbose_name': '게임플레이 히스토리',
                'verbose_name_plural': '게임플레이 히스토리',
                'ordering': ['-started_at'],
            },
        ),
    ]
