# Generated by Django 5.2.2 on 2025-10-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '수동 저장 결제 트랜잭션',
                'verbose_name_plural': '수동 저장 결제 트랜잭션',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymenttransaction',),
        ),
    ]
