# Generated by Django 5.2.2 on 2025-10-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_digitalfile_file_digita_price_d_79c941_idx_and_more'),
        ('ln_payment', '0004_paymenttransaction_live_lecture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='file_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='file.fileorder', verbose_name='연결 파일 주문'),
        ),
    ]
