FEATURE_ITEM_TYPE_PRODUCT = 'product'
FEATURE_ITEM_TYPE_MEETUP = 'meetup'
FEATURE_ITEM_TYPE_LIVE = 'live_lecture'
FEATURE_ITEM_TYPE_FILE = 'digital_file'

FEATURE_ITEM_TYPE_CHOICES = (
    (FEATURE_ITEM_TYPE_PRODUCT, '상품'),
    (FEATURE_ITEM_TYPE_MEETUP, '밋업'),
    (FEATURE_ITEM_TYPE_LIVE, '라이브 강의'),
    (FEATURE_ITEM_TYPE_FILE, '디지털 파일'),
)

STORE_MAIN_DISPLAY_LIMITS = {
    FEATURE_ITEM_TYPE_PRODUCT: 8,
    FEATURE_ITEM_TYPE_MEETUP: 8,
    FEATURE_ITEM_TYPE_LIVE: 8,
    FEATURE_ITEM_TYPE_FILE: 8,
}
