# Generated by Django 5.2.2 on 2025-06-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text='라이트닝 공개키 (hex)', max_length=66, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_lightning_user',
                'indexes': [models.Index(fields=['public_key'], name='accounts_li_public__5e85e2_idx')],
            },
        ),
    ]
