# Generated by Django 5.2.2 on 2025-06-23 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text='라이트닝 공개키 (hex)', max_length=66, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_lightning_user',
                'indexes': [models.Index(fields=['public_key'], name='accounts_li_public__5e85e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LNURLAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.CharField(help_text='LNURL-auth k1 파라미터', max_length=64, unique=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='세션 UUID', unique=True)),
                ('public_key', models.CharField(blank=True, help_text='사용자 공개키 (hex)', max_length=66)),
                ('signature', models.CharField(blank=True, help_text='서명 (hex)', max_length=128)),
                ('is_verified', models.BooleanField(default=False, help_text='서명 검증 완료 여부')),
                ('is_used', models.BooleanField(default=False, help_text='인증 사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='만료 시간')),
                ('verified_at', models.DateTimeField(blank=True, help_text='검증 완료 시간', null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='인증 사용 시간', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='인증된 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_lnurl_auth',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['k1'], name='accounts_ln_k1_346e37_idx'), models.Index(fields=['session_id'], name='accounts_ln_session_5dcb84_idx'), models.Index(fields=['public_key'], name='accounts_ln_public__4f5c00_idx'), models.Index(fields=['is_verified', 'is_used'], name='accounts_ln_is_veri_b5c6ca_idx'), models.Index(fields=['created_at'], name='accounts_ln_created_4fb970_idx')],
            },
        ),
    ]
