# Generated by Django 5.2.2 on 2025-01-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS accounts_lnurl_auth CASCADE;",
            reverse_sql="-- 테이블 복구는 지원하지 않음"
        ),
    ]
