# Generated by Django 5.2.2 on 2025-07-03 05:56

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_lnurl_auth_table'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupParticipant',
            fields=[
            ],
            options={
                'verbose_name': '밋업 참가자',
                'verbose_name_plural': '밋업 참가자 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
