# Generated by Django 5.2.2 on 2025-09-25 05:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_meetupparticipant'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
            ],
            options={
                'verbose_name': '사용자별 구매 내역',
                'verbose_name_plural': '사용자별 구매 내역',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
