# Generated by Django 5.2.2 on 2025-11-01 01:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpurchasehistory'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMyPageHistory',
            fields=[
            ],
            options={
                'verbose_name': '사용자 마이페이지 이력',
                'verbose_name_plural': '사용자 마이페이지 이력',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
