# Generated by Django 5.2.2 on 2025-12-01 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermypagehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_password_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '임시 비밀번호',
                'verbose_name_plural': '임시 비밀번호',
                'db_table': 'accounts_temporary_password',
            },
        ),
    ]
