# Generated by Django 5.2.2 on 2025-12-02 22:59

import secrets
import string
import time

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ALPHABET = string.digits + string.ascii_lowercase


def _to_base36(number: int) -> str:
    if number == 0:
        return '0'

    digits = []
    while number:
        number, remainder = divmod(number, 36)
        digits.append(ALPHABET[remainder])
    return ''.join(reversed(digits))


def _generate_public_id(length: int = 27) -> str:
    timestamp = int(time.time() * 1000)
    ts_part = _to_base36(timestamp)
    random_length = max(length - len(ts_part) - 1, 8)
    random_part = ''.join(secrets.choice(ALPHABET) for _ in range(random_length))
    return f"c{ts_part}{random_part}"[:length]


def seed_public_ids(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)
    UserPublicId = apps.get_model('accounts', 'UserPublicId')

    def _generate_unique():
        while True:
            candidate = _generate_public_id()
            if not UserPublicId.objects.filter(public_id=candidate).exists():
                return candidate

    for user in User.objects.all():
        UserPublicId.objects.get_or_create(
            user=user,
            defaults={'public_id': _generate_unique()},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_temporarypassword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublicId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=accounts.models.generate_public_id, help_text='외부 노출용 CUID', max_length=27, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 공개 ID',
                'verbose_name_plural': '사용자 공개 ID',
                'db_table': 'accounts_user_public_id',
            },
        ),
        migrations.RunPython(seed_public_ids, migrations.RunPython.noop),
    ]
