# Generated by Django 5.2.2 on 2025-12-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userpublicid'),
        ('stores', '0033_storefeatureditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePurchaseCleanupProxy',
            fields=[
            ],
            options={
                'verbose_name': '스토어 구입 이력 삭제',
                'verbose_name_plural': '스토어 구입 이력 삭제',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stores.store',),
        ),
    ]
