# Generated by Django 5.2.2 on 2025-12-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_storepurchasecleanupproxy'),
        ('orders', '0015_alter_order_delivery_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorePurchaseCleanupProxy',
        ),
        migrations.CreateModel(
            name='OrderCleanupProxy',
            fields=[
            ],
            options={
                'verbose_name': '스토어 구입 이력',
                'verbose_name_plural': '스토어 구입 이력',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
