# Generated by Django 5.2.2 on 2025-12-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_storepurchasecleanupproxy_ordercleanupproxy'),
        ('file', '0010_filemanualpaymenttransaction_and_more'),
        ('lecture', '0006_livelecturemanualpaymenttransaction_and_more'),
        ('meetup', '0018_meetupmanualpaymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOrderCleanupProxy',
            fields=[
            ],
            options={
                'verbose_name': '디지털 파일 구입 이력',
                'verbose_name_plural': '디지털 파일 구입 이력',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('file.fileorder',),
        ),
        migrations.CreateModel(
            name='LiveLectureOrderCleanupProxy',
            fields=[
            ],
            options={
                'verbose_name': '라이브 강의 구입 이력',
                'verbose_name_plural': '라이브 강의 구입 이력',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lecture.livelectureorder',),
        ),
        migrations.CreateModel(
            name='MeetupOrderCleanupProxy',
            fields=[
            ],
            options={
                'verbose_name': '밋업 구입 이력',
                'verbose_name_plural': '밋업 구입 이력',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meetup.meetuporder',),
        ),
    ]
