# Generated by Django 5.2.2 on 2025-12-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fileordercleanupproxy_livelectureordercleanupproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercleanupproxy',
            options={'verbose_name': '상품 구입 이력', 'verbose_name_plural': '상품 구입 이력'},
        ),
    ]
