# Generated by Django 5.2.2 on 2026-02-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_nostruser'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nostruser',
            new_name='accounts_no_public__df3e9b_idx',
            old_name='accounts_nos_public__3fe23f_idx',
        ),
    ]
