# Generated by Django 5.2.2 on 2025-12-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='satoshop', max_length=120, verbose_name='봇 이름')),
                ('token', models.CharField(max_length=220, verbose_name='봇 토큰')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '디스코드 봇',
                'verbose_name_plural': '디스코드 봇',
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=120, verbose_name='서버 이름')),
                ('channel_name', models.CharField(blank=True, max_length=120, verbose_name='채널 이름')),
                ('channel_id', models.CharField(max_length=40, verbose_name='채널 ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='satoshop_bot.discordbot', verbose_name='연결 봇')),
            ],
            options={
                'verbose_name': '디스코드 채널',
                'verbose_name_plural': '디스코드 채널',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('bot', 'channel_id'), name='unique_discord_bot_channel')],
            },
        ),
    ]
