# Generated by Django 5.2.2 on 2026-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satoshop_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordbot',
            name='application_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='애플리케이션 ID'),
        ),
        migrations.AddField(
            model_name='discordbot',
            name='public_key',
            field=models.CharField(blank=True, help_text='디스코드 Developer Portal의 Public Key(16진수)', max_length=128, verbose_name='인터랙션 공개키'),
        ),
    ]
