# Generated by Django 5.2.2 on 2025-06-28 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0023_add_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='stores.store')),
            ],
            options={
                'verbose_name': '메뉴 카테고리',
                'verbose_name_plural': '메뉴 카테고리',
                'ordering': ['order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('description', models.TextField(verbose_name='메뉴 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/%Y/%m/%d/', verbose_name='메뉴 이미지')),
                ('price_display', models.CharField(choices=[('sats', '사토시 고정'), ('krw', '원화 비율 연동')], default='sats', max_length=10, verbose_name='가격 표시 방식')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='가격')),
                ('price_krw', models.PositiveIntegerField(blank=True, null=True, verbose_name='원화 가격')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='할인 적용')),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='할인가')),
                ('discounted_price_krw', models.PositiveIntegerField(blank=True, null=True, verbose_name='원화 할인가')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_temporarily_out_of_stock', models.BooleanField(default=False, verbose_name='일시품절')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.store')),
                ('categories', models.ManyToManyField(blank=True, related_name='menus', to='menu.menucategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='옵션명')),
                ('values', models.TextField(verbose_name='옵션값들 (JSON)')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 선택')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.menu')),
            ],
            options={
                'verbose_name': '메뉴 옵션',
                'verbose_name_plural': '메뉴 옵션',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
