# Generated by Django 5.2.2 on 2025-06-28 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_url', models.URLField(max_length=800, verbose_name='파일 URL')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기 (bytes)')),
                ('width', models.PositiveIntegerField(default=500, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=500, verbose_name='이미지 높이')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menu')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '메뉴 이미지',
                'verbose_name_plural': '메뉴 이미지들',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['menu', 'order'], name='menu_menuim_menu_id_2c9cde_idx'), models.Index(fields=['uploaded_at'], name='menu_menuim_uploade_f92b61_idx')],
            },
        ),
    ]
