# Generated by Django 5.2.2 on 2025-06-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name'], 'verbose_name': '메뉴 카테고리', 'verbose_name_plural': '메뉴 카테고리'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='순서'),
        ),
    ]
