# Generated by Django 5.2.2 on 2025-06-28 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인가'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격'),
        ),
    ]
