# Generated by Django 5.2.2 on 2025-06-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_discounted_price_alter_menu_price'),
        ('stores', '0023_add_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '주문 대기'), ('payment_pending', '결제 대기'), ('paid', '결제 완료'), ('cancelled', '주문 취소'), ('expired', '주문 만료')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('total_amount', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='총 금액')),
                ('payment_hash', models.CharField(blank=True, max_length=100, verbose_name='결제 해시')),
                ('customer_info', models.JSONField(blank=True, default=dict, help_text='비회원 주문 시 고객 정보 저장', verbose_name='고객 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문 시간')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_orders', to='stores.store', verbose_name='스토어')),
            ],
            options={
                'verbose_name': '메뉴 주문',
                'verbose_name_plural': '메뉴 주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('menu_price', models.PositiveIntegerField(verbose_name='메뉴 가격')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='옵션명: 선택값 형태로 저장', verbose_name='선택된 옵션들')),
                ('options_price', models.PositiveIntegerField(default=0, verbose_name='옵션 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='메뉴')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menuorder', verbose_name='주문')),
            ],
            options={
                'verbose_name': '메뉴 주문 아이템',
                'verbose_name_plural': '메뉴 주문 아이템들',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuorder',
            index=models.Index(fields=['store', 'created_at'], name='menu_menuor_store_i_b3ca77_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorder',
            index=models.Index(fields=['status'], name='menu_menuor_status_2ea7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorder',
            index=models.Index(fields=['order_number'], name='menu_menuor_order_n_ab3eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorder',
            index=models.Index(fields=['payment_hash'], name='menu_menuor_payment_5eaeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['order'], name='menu_menuor_order_i_803bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['menu'], name='menu_menuor_menu_id_fe6aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['created_at'], name='menu_menuor_created_13b4c8_idx'),
        ),
    ]
