# Generated by Django 5.2.2 on 2025-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuorder_menuorderitem_and_more'),
        ('stores', '0023_add_email_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['store'], name='menu_menu_store_i_17837f_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_active'], name='menu_menu_is_acti_ee88d5_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['store', 'is_active'], name='menu_menu_store_i_4873d5_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['created_at'], name='menu_menu_created_1667a0_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['updated_at'], name='menu_menu_updated_66833c_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['price_display'], name='menu_menu_price_d_7ac2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_discounted'], name='menu_menu_is_disc_c8914b_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_temporarily_out_of_stock'], name='menu_menu_is_temp_bcf888_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['store', 'is_active', 'created_at'], name='menu_menu_store_i_c03b33_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['store'], name='menu_menuca_store_i_2a35a8_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['order'], name='menu_menuca_order_52271f_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['store', 'order'], name='menu_menuca_store_i_1cba87_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['created_at'], name='menu_menuca_created_f0f124_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['updated_at'], name='menu_menuca_updated_eef158_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['menu'], name='menu_menuop_menu_id_566285_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['order'], name='menu_menuop_order_152d02_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['menu', 'order'], name='menu_menuop_menu_id_8803ef_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['is_required'], name='menu_menuop_is_requ_fb4717_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['created_at'], name='menu_menuop_created_aea5a1_idx'),
        ),
    ]
