# Generated by Django 5.2.2 on 2025-07-06 23:24

from django.db import migrations


def update_order_number_format(apps, schema_editor):
    """기존 주문번호를 새로운 형식으로 업데이트"""
    MenuOrder = apps.get_model('menu', 'MenuOrder')
    
    # 모든 주문을 가져와서 생성일시 순으로 정렬
    orders = MenuOrder.objects.all().order_by('created_at')
    
    for order in orders:
        # 새로운 주문번호 생성: MENU-YYYYMMDD-HHMMSS
        created_at = order.created_at
        new_order_number = f"MENU-{created_at.strftime('%Y%m%d')}-{created_at.strftime('%H%M%S')}"
        
        # 중복 확인 및 처리
        counter = 0
        original_new_order_number = new_order_number
        
        while MenuOrder.objects.filter(order_number=new_order_number).exists():
            counter += 1
            # 중복이 있으면 뒤에 카운터 추가
            new_order_number = f"{original_new_order_number}-{counter:02d}"
        
        # 주문번호 업데이트
        order.order_number = new_order_number
        order.save(update_fields=['order_number'])


def reverse_order_number_format(apps, schema_editor):
    """마이그레이션 롤백 시 실행될 함수 (실제로는 되돌릴 수 없음)"""
    # 롤백은 복잡하므로 경고 메시지만 출력
    print("WARNING: 주문번호 형식 변경은 되돌릴 수 없습니다.")


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_menu_menu_store_i_17837f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(update_order_number_format, reverse_order_number_format),
    ]
