# Generated by Django 5.2.2 on 2025-07-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_update_order_number_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='주문번호'),
        ),
    ]
