# Generated by Django 5.2.2 on 2025-07-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuorder_order_number'),
        ('menu', '0007_update_order_number_to_new_format'),
    ]

    operations = [
    ]
