# Generated by Django 5.2.2 on 2025-06-18 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='공지 고정')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.notice', verbose_name='공지사항')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.noticecomment', verbose_name='부모 댓글')),
            ],
            options={
                'verbose_name': '공지사항 댓글',
                'verbose_name_plural': '공지사항 댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active', '-created_at'], name='boards_noti_is_acti_6879cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_pinned', '-created_at'], name='boards_noti_is_pinn_dd54c7_idx'),
        ),
        migrations.AddIndex(
            model_name='noticecomment',
            index=models.Index(fields=['notice', 'is_active', 'created_at'], name='boards_noti_notice__c5a2ce_idx'),
        ),
    ]
