# Generated by Django 5.2.2 on 2025-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='순서번호'),
        ),
    ]
