# Generated by Django 5.2.2 on 2025-06-18 23:30

from django.db import migrations, models


def assign_sequence_numbers(apps, schema_editor):
    """기존 공지사항들에 순서 번호 할당"""
    Notice = apps.get_model('boards', 'Notice')
    
    # 이미 할당된 가장 큰 순서 번호 찾기
    max_sequence = Notice.objects.filter(sequence_number__isnull=False).aggregate(
        max_seq=models.Max('sequence_number')
    )['max_seq'] or 0
    
    # 생성일 순으로 정렬하여 순서 번호 할당
    notices = Notice.objects.filter(sequence_number__isnull=True).order_by('created_at')
    
    for index, notice in enumerate(notices, start=max_sequence + 1):
        notice.sequence_number = index
        notice.save(update_fields=['sequence_number'])


def reverse_assign_sequence_numbers(apps, schema_editor):
    """순서 번호 할당 롤백"""
    Notice = apps.get_model('boards', 'Notice')
    Notice.objects.update(sequence_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_notice_sequence_number'),
    ]

    operations = [
        migrations.RunPython(assign_sequence_numbers, reverse_assign_sequence_numbers),
    ]
