# Generated by Django 5.2.2 on 2025-06-19 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20250619_0830'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticecomment',
            options={'ordering': ['-created_at'], 'verbose_name': '공지사항 댓글', 'verbose_name_plural': '공지사항 댓글'},
        ),
        migrations.RemoveIndex(
            model_name='noticecomment',
            name='boards_noti_notice__c5a2ce_idx',
        ),
        migrations.AddIndex(
            model_name='noticecomment',
            index=models.Index(fields=['notice', 'is_active', '-created_at'], name='boards_noti_notice__8085ad_idx'),
        ),
    ]
