# Generated by Django 5.2.2 on 2025-07-01 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_noticecomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['sequence_number'], name='boards_noti_sequenc_040276_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['author'], name='boards_noti_author__172bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['views'], name='boards_noti_views_7eaf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active', 'is_pinned', 'created_at'], name='boards_noti_is_acti_a60c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at'], name='boards_noti_created_b18f71_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['updated_at'], name='boards_noti_updated_4ac4b9_idx'),
        ),
    ]
