# Generated by Django 5.2.2 on 2025-07-27 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_notice_boards_noti_sequenc_040276_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '밈 태그',
                'verbose_name_plural': '밈 태그',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='boards_meme_name_568a67_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('image_path', models.CharField(max_length=500, verbose_name='이미지 경로')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('thumbnail_path', models.CharField(max_length=500, verbose_name='썸네일 경로')),
                ('thumbnail_url', models.URLField(max_length=500, verbose_name='썸네일 URL')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='파일 크기')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='이미지 높이')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='memes', to='boards.memetag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '밈 게시글',
                'verbose_name_plural': '밈 게시글',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='boards_meme_is_acti_fe3ca9_idx'), models.Index(fields=['author'], name='boards_meme_author__4efc42_idx'), models.Index(fields=['views'], name='boards_meme_views_18e48c_idx'), models.Index(fields=['created_at'], name='boards_meme_created_50824b_idx'), models.Index(fields=['updated_at'], name='boards_meme_updated_f44067_idx')],
            },
        ),
    ]
