# Generated by Django 5.2.2 on 2025-07-27 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_memetag_memepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memepost',
            name='boards_meme_author__4efc42_idx',
        ),
        migrations.AlterField(
            model_name='memepost',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='memetag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='태그명'),
        ),
        migrations.AddIndex(
            model_name='memepost',
            index=models.Index(fields=['author', 'is_active'], name='boards_meme_author__127793_idx'),
        ),
        migrations.AddIndex(
            model_name='memepost',
            index=models.Index(fields=['title'], name='boards_meme_title_0c346c_idx'),
        ),
        migrations.AddIndex(
            model_name='memetag',
            index=models.Index(fields=['created_at'], name='boards_meme_created_1cb602_idx'),
        ),
    ]
