# Generated by Django 5.2.2 on 2025-07-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_add_meme_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memepost',
            name='detail_copy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='상세 복사 횟수'),
        ),
        migrations.AddField(
            model_name='memepost',
            name='list_copy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='목록 복사 횟수'),
        ),
        migrations.AddField(
            model_name='memepost',
            name='list_view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='목록 보기 횟수'),
        ),
    ]
