# Generated by Django 5.2.2 on 2025-07-27 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_add_meme_click_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memepost',
            index=models.Index(fields=['list_copy_count', 'list_view_count', 'detail_copy_count'], name='boards_meme_list_co_8b8847_idx'),
        ),
    ]
