# Generated by Django 5.2.2 on 2025-08-29 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_add_meme_stats_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image_path', models.CharField(max_length=500, verbose_name='이미지 경로')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('thumbnail_path', models.CharField(max_length=500, verbose_name='썸네일 경로')),
                ('thumbnail_url', models.URLField(max_length=500, verbose_name='썸네일 URL')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='파일 크기')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='이미지 높이')),
                ('views', models.PositiveIntegerField(db_index=True, default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='순서')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hall_of_fame', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Hall of Fame',
                'verbose_name_plural': 'Hall of Fame',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order', '-created_at'], name='boards_hall_is_acti_50b8d0_idx'), models.Index(fields=['user', 'is_active'], name='boards_hall_user_id_e0d859_idx'), models.Index(fields=['order'], name='boards_hall_order_3230f5_idx'), models.Index(fields=['created_at'], name='boards_hall_created_43d73f_idx')],
            },
        ),
    ]
