# Generated by Django 5.2.2 on 2025-08-29 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_halloffame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFamePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_upload', models.BooleanField(default=True, verbose_name='업로드 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='권한 부여일')),
            ],
            options={
                'verbose_name': 'Hall of Fame 권한',
                'verbose_name_plural': 'Hall of Fame 권한',
            },
        ),
        migrations.AlterModelOptions(
            name='halloffame',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hall of Fame', 'verbose_name_plural': 'Hall of Fame'},
        ),
        migrations.RemoveIndex(
            model_name='halloffame',
            name='boards_hall_is_acti_50b8d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='halloffame',
            name='boards_hall_user_id_e0d859_idx',
        ),
        migrations.RemoveIndex(
            model_name='halloffame',
            name='boards_hall_order_3230f5_idx',
        ),
        migrations.AddField(
            model_name='halloffame',
            name='month',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='월'),
        ),
        migrations.AddField(
            model_name='halloffame',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2024, verbose_name='년도'),
        ),
        migrations.AlterUniqueTogether(
            name='halloffame',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='halloffame',
            index=models.Index(fields=['year', 'month', '-created_at'], name='boards_hall_year_c35571_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffame',
            index=models.Index(fields=['is_active', '-created_at'], name='boards_hall_is_acti_612600_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffame',
            index=models.Index(fields=['year'], name='boards_hall_year_500aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffame',
            index=models.Index(fields=['month'], name='boards_hall_month_0c1c04_idx'),
        ),
        migrations.AddField(
            model_name='halloffamepermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='권한 부여자'),
        ),
        migrations.AddField(
            model_name='halloffamepermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='description',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='order',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='title',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='user',
        ),
    ]