# Generated by Django 5.2.2 on 2025-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_update_hall_of_fame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2025, verbose_name='년도'),
        ),
    ]
