# Generated by Django 5.2.2 on 2025-09-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_halloffame_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='halloffame',
            unique_together=set(),
        ),
    ]
