# Generated by Django 5.2.2 on 2025-06-10 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(help_text='스토어 접속 경로로 사용됩니다. (예: mystore)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='스토어 아이디는 영문, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능합니다.', regex='^[a-zA-Z0-9_-]+$')])),
                ('store_name', models.CharField(help_text='스토어 이름', max_length=100)),
                ('store_description', models.TextField(blank=True, help_text='스토어 설명 (Markdown 형식)')),
                ('owner_name', models.CharField(help_text='주인장 이름', max_length=50)),
                ('owner_phone', models.CharField(blank=True, help_text='주인장 휴대전화', max_length=20)),
                ('owner_email', models.EmailField(blank=True, help_text='주인장 이메일', max_length=254)),
                ('chat_channel', models.URLField(help_text='대화채널 (오픈카톡, 텔레그램, 라인, 엑스 등)')),
                ('blink_api_info_encrypted', models.TextField(blank=True, help_text='암호화된 블링크 API 정보')),
                ('blink_wallet_id_encrypted', models.TextField(blank=True, help_text='암호화된 블링크 월렛 ID')),
                ('is_active', models.BooleanField(default=False, help_text='스토어 활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스토어',
                'verbose_name_plural': '스토어들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCreationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1, help_text='현재 단계 (1-5)')),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('step4_completed', models.BooleanField(default=False)),
                ('step5_completed', models.BooleanField(default=False)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_step', to='stores.store')),
            ],
            options={
                'verbose_name': '스토어 생성 단계',
                'verbose_name_plural': '스토어 생성 단계들',
            },
        ),
    ]
