# Generated by Django 5.2.2 on 2025-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hero_color1',
            field=models.CharField(default='#667eea', help_text='히어로 섹션 그라데이션 시작 색상', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='hero_color2',
            field=models.CharField(default='#764ba2', help_text='히어로 섹션 그라데이션 끝 색상', max_length=7),
        ),
    ]
