# Generated by Django 5.2.2 on 2025-06-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_hero_color1_store_hero_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hero_text_color',
            field=models.CharField(default='#ffffff', help_text='히어로 섹션 텍스트 색상', max_length=7),
        ),
    ]
