# Generated by Django 5.2.2 on 2025-06-11 01:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_hero_text_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedStoreId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='사용자가 스토어 아이디로 사용할 수 없는 예약어', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='예약어는 영문, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능합니다.', regex='^[a-zA-Z0-9_-]+$')])),
                ('description', models.CharField(blank=True, help_text='예약어 설명', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='예약어 활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='등록한 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스토어 아이디 예약어',
                'verbose_name_plural': '스토어 아이디 예약어들',
                'ordering': ['keyword'],
            },
        ),
    ]
