# Generated by Django 5.2.2 on 2025-06-11 01:30

from django.db import migrations


def add_default_reserved_keywords(apps, schema_editor):
    """기본 예약어들을 추가"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # 기본 예약어 목록
    default_keywords = [
        # 시스템 예약어
        ('admin', '관리자 페이지'),
        ('api', 'API 엔드포인트'),
        ('static', '정적 파일'),
        ('media', '미디어 파일'),
        ('favicon', '파비콘 파일'),
        ('robots', 'robots.txt'),
        ('sitemap', 'sitemap.xml'),
        
        # 일반적인 웹사이트 경로
        ('www', 'www 서브도메인'),
        ('mail', '메일 서비스'),
        ('ftp', 'FTP 서비스'),
        ('blog', '블로그'),
        ('news', '뉴스'),
        ('shop', '쇼핑몰'),
        ('store', '스토어'),
        ('user', '사용자'),
        ('users', '사용자들'),
        ('account', '계정'),
        ('accounts', '계정들'),
        ('profile', '프로필'),
        ('settings', '설정'),
        ('config', '설정'),
        ('help', '도움말'),
        ('support', '지원'),
        ('contact', '연락처'),
        ('about', '소개'),
        ('home', '홈'),
        ('index', '인덱스'),
        ('login', '로그인'),
        ('logout', '로그아웃'),
        ('register', '회원가입'),
        ('signup', '가입'),
        ('signin', '로그인'),
        
        # 프로그래미응 관련
        ('test', '테스트'),
        ('dev', '개발'),
        ('debug', '디버그'),
        ('error', '오류'),
        ('404', '404 오류'),
        ('500', '500 오류'),
        
        # 보안 관련
        ('security', '보안'),
        ('secure', '보안'),
        ('ssl', 'SSL'),
        ('https', 'HTTPS'),
        
        # 비즈니스 관련
        ('business', '비즈니스'),
        ('enterprise', '기업'),
        ('pro', '프로'),
        ('premium', '프리미엄'),
        
        # 일반적인 단어들
        ('app', '앱'),
        ('mobile', '모바일'),
        ('web', '웹'),
        ('site', '사이트'),
        ('page', '페이지'),
        ('service', '서비스'),
        ('system', '시스템'),
        ('root', '루트'),
        ('null', 'NULL'),
        ('undefined', '정의되지 않음'),
        ('temp', '임시'),
        ('tmp', '임시'),
        ('cache', '캐시'),
        ('public', '공개'),
        ('private', '비공개'),
        ('internal', '내부'),
        ('external', '외부'),
    ]
    
    # 예약어 생성 (이미 존재하지 않는 경우에만)
    for keyword, description in default_keywords:
        ReservedStoreId.objects.get_or_create(
            keyword=keyword,
            defaults={
                'description': description,
                'is_active': True
            }
        )


def remove_default_reserved_keywords(apps, schema_editor):
    """마이그레이션 롤백 시 기본 예약어들을 제거"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # 기본 예약어들만 삭제 (created_by가 null인 것들)
    ReservedStoreId.objects.filter(created_by__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_reservedstoreid'),
    ]

    operations = [
        migrations.RunPython(
            add_default_reserved_keywords,
            remove_default_reserved_keywords
        ),
    ]
