# Generated by Django 5.2.2 on 2025-06-11 01:35

from django.db import migrations


def add_additional_reserved_keywords(apps, schema_editor):
    """추가 예약어들을 추가"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # 추가 예약어 목록
    additional_keywords = [
        # 비트코인/크립토 관련
        ('satoshop', 'SatoShop 브랜드명'),
        ('bsl', 'Bitcoin Standard Library'),
        ('btc', '비트코인 약어'),
        ('bitcoin', '비트코인'),
        ('sats', '사토시 복수형'),
        ('sat', '사토시 단수형'),
        ('satoshi', '사토시'),
        ('nakamoto', '나카모토 사토시'),
        
        # 일반 서비스 관련
        ('course', '강의/코스'),
        ('game', '게임'),
        ('shop', '쇼핑몰'),
        ('menu', '메뉴'),
        ('menus', '메뉴들'),
        ('shops', '쇼핑몰들'),
        ('games', '게임들'),
        ('mall', '쇼핑몰'),
        ('malls', '쇼핑몰들'),
        ('magazine', '잡지'),
        ('magazines', '잡지들'),
        ('news', '뉴스'),
        ('paper', '논문/신문'),
        ('papers', '논문들/신문들'),
    ]
    
    # 예약어 생성 (이미 존재하지 않는 경우에만)
    for keyword, description in additional_keywords:
        ReservedStoreId.objects.get_or_create(
            keyword=keyword,
            defaults={
                'description': description,
                'is_active': True
            }
        )


def remove_additional_reserved_keywords(apps, schema_editor):
    """마이그레이션 롤백 시 추가 예약어들을 제거"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # 추가 예약어들만 삭제
    additional_keywords = [
        'satoshop', 'bsl', 'btc', 'bitcoin', 'sats', 'sat', 'satoshi', 'nakamoto',
        'course', 'game', 'shop', 'menu', 'menus', 'shops', 'games', 'mall', 
        'malls', 'magazine', 'magazines', 'news', 'paper', 'papers'
    ]
    
    ReservedStoreId.objects.filter(keyword__in=additional_keywords).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20250611_1030'),
    ]

    operations = [
        migrations.RunPython(
            add_additional_reserved_keywords,
            remove_additional_reserved_keywords
        ),
    ]
