# Generated by Django 5.2.2 on 2025-06-11 01:41

from django.db import migrations


def add_my_mini_keywords(apps, schema_editor):
    """my/mini 관련 예약어들을 추가"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # my/mini 관련 예약어 목록
    my_mini_keywords = [
        ('myhome', '마이홈'),
        ('myshop', '마이샵'),
        ('mystore', '마이스토어'),
        ('minihome', '미니홈'),
        ('minishop', '미니샵'),
        ('minimall', '미니몰'),
        ('mymall', '마이몰'),
    ]
    
    # 예약어 생성 (이미 존재하지 않는 경우에만)
    for keyword, description in my_mini_keywords:
        ReservedStoreId.objects.get_or_create(
            keyword=keyword,
            defaults={
                'description': description,
                'is_active': True
            }
        )


def remove_my_mini_keywords(apps, schema_editor):
    """마이그레이션 롤백 시 my/mini 관련 예약어들을 제거"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # my/mini 관련 예약어들만 삭제
    my_mini_keywords = [
        'myhome', 'myshop', 'mystore', 'minihome', 'minishop', 'minimall', 'mymall'
    ]
    
    ReservedStoreId.objects.filter(keyword__in=my_mini_keywords).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20250611_1039'),
    ]

    operations = [
        migrations.RunPython(
            add_my_mini_keywords,
            remove_my_mini_keywords
        ),
    ]
