# Generated by Django 5.2.2 on 2025-06-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20250611_1041'),
    ]

    operations = [
    ]
