# Generated by Django 5.2.2 on 2025-06-11 01:42

from django.db import migrations


def add_time_keywords(apps, schema_editor):
    """time 관련 예약어들을 추가"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # time 관련 예약어 목록
    time_keywords = [
        ('time', '시간'),
        ('timechain', '타임체인 (비트코인 블록체인의 다른 이름)'),
    ]
    
    # 예약어 생성 (이미 존재하지 않는 경우에만)
    for keyword, description in time_keywords:
        ReservedStoreId.objects.get_or_create(
            keyword=keyword,
            defaults={
                'description': description,
                'is_active': True
            }
        )


def remove_time_keywords(apps, schema_editor):
    """마이그레이션 롤백 시 time 관련 예약어들을 제거"""
    ReservedStoreId = apps.get_model('stores', 'ReservedStoreId')
    
    # time 관련 예약어들만 삭제
    time_keywords = ['time', 'timechain']
    
    ReservedStoreId.objects.filter(keyword__in=time_keywords).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20250611_1041'),
    ]

    operations = [
        migrations.RunPython(
            add_time_keywords,
            remove_time_keywords
        ),
    ]
