# Generated by Django 5.2.2 on 2025-06-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20250611_1042'),
        ('stores', '0011_auto_20250611_1042'),
    ]

    operations = [
    ]
