# Generated by Django 5.2.2 on 2025-06-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_merge_0010_auto_20250611_1042_0011_auto_20250611_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='소프트 삭제 시간', null=True),
        ),
    ]
