# Generated by Django 5.2.2 on 2025-06-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_store_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStore',
            fields=[
            ],
            options={
                'verbose_name': '삭제된 스토어',
                'verbose_name_plural': '삭제된 스토어들',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stores.store',),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner',), name='unique_active_store_per_owner'),
        ),
    ]
