# Generated by Django 5.2.2 on 2025-06-12 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_fix_store_id_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_url', models.URLField(verbose_name='파일 URL')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('width', models.PositiveIntegerField(default=1000, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=563, verbose_name='이미지 높이')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.store')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '스토어 이미지',
                'verbose_name_plural': '스토어 이미지들',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['store', 'order'], name='stores_stor_store_i_fb0e00_idx')],
            },
        ),
    ]
