# Generated by Django 5.2.2 on 2025-06-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_storeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='file_url',
            field=models.URLField(max_length=800, verbose_name='파일 URL'),
        ),
    ]
