# Generated by Django 5.2.2 on 2025-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_storeimage_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기 (bytes)'),
        ),
    ]
