# Generated by Django 5.2.2 on 2025-06-12 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_alter_storeimage_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니들',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '주문 대기'), ('payment_pending', '결제 대기'), ('paid', '결제 완료'), ('shipped', '배송 중'), ('delivered', '배송 완료'), ('cancelled', '주문 취소'), ('refunded', '환불 완료')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='주문자 이름')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='주문자 연락처')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='주문자 이메일')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='주소')),
                ('shipping_detail_address', models.CharField(max_length=100, verbose_name='상세주소')),
                ('order_memo', models.TextField(blank=True, verbose_name='주문 메모')),
                ('subtotal', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='상품 금액')),
                ('shipping_fee', models.PositiveIntegerField(help_text='원 단위', verbose_name='배송비')),
                ('total_amount', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='총 금액')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='결제 ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_info_deleted_at', models.DateTimeField(blank=True, help_text='3개월 후 자동 삭제', null=True, verbose_name='개인정보 삭제 시간')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(help_text='마크다운 형식', verbose_name='설명')),
                ('price', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='가격')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='할인 여부')),
                ('discounted_price', models.PositiveIntegerField(blank=True, help_text='사토시 단위', null=True, verbose_name='할인가격')),
                ('shipping_fee', models.PositiveIntegerField(default=3000, help_text='원 단위', verbose_name='배송비')),
                ('completion_message', models.TextField(blank=True, help_text='결제 완료 후 보여줄 메시지', verbose_name='결제완료 안내메시지')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매 중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='상품명')),
                ('product_price', models.PositiveIntegerField(verbose_name='상품 가격')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='옵션명: 선택지명 형태로 저장', verbose_name='선택된 옵션들')),
                ('options_price', models.PositiveIntegerField(default=0, verbose_name='옵션 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
            options={
                'verbose_name': '주문 아이템',
                'verbose_name_plural': '주문 아이템들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='옵션ID: 선택지ID 형태로 저장', verbose_name='선택된 옵션들')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
            options={
                'verbose_name': '장바구니 아이템',
                'verbose_name_plural': '장바구니 아이템들',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_url', models.URLField(max_length=800, verbose_name='파일 URL')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기 (bytes)')),
                ('width', models.PositiveIntegerField(default=500, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=500, verbose_name='이미지 높이')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.product')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지들',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stores.product')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션들',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='옵션 종류명')),
                ('price', models.IntegerField(default=0, help_text='사토시 단위', verbose_name='추가 가격')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='stores.productoption')),
            ],
            options={
                'verbose_name': '상품 옵션 선택지',
                'verbose_name_plural': '상품 옵션 선택지들',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='스토어명')),
                ('total_amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('purchase_date', models.DateTimeField(verbose_name='구매 날짜')),
                ('auto_delete_at', models.DateTimeField(help_text='구매 후 3개월 뒤 자동 삭제', verbose_name='자동 삭제 예정일')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='stores.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구매 내역',
                'verbose_name_plural': '구매 내역들',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='stores_orde_user_id_633fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'created_at'], name='stores_orde_store_i_ecfd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='stores_orde_status_b70452_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='stores_orde_order_n_765b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='stores_prod_store_i_180ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='stores_prod_created_62f260_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='stores_prod_product_616445_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_option_name'),
        ),
        migrations.AddConstraint(
            model_name='productoptionchoice',
            constraint=models.UniqueConstraint(fields=('option', 'name'), name='unique_option_choice_name'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['user', 'purchase_date'], name='stores_purc_user_id_eae375_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['auto_delete_at'], name='stores_purc_auto_de_ae34f1_idx'),
        ),
    ]
