# Generated by Django 5.2.2 on 2025-06-17 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_remove_cart_user_remove_cartitem_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservedstoreid',
            index=models.Index(fields=['keyword'], name='stores_rese_keyword_695525_idx'),
        ),
        migrations.AddIndex(
            model_name='reservedstoreid',
            index=models.Index(fields=['is_active'], name='stores_rese_is_acti_585125_idx'),
        ),
        migrations.AddIndex(
            model_name='reservedstoreid',
            index=models.Index(fields=['created_at'], name='stores_rese_created_d44445_idx'),
        ),
        migrations.AddIndex(
            model_name='reservedstoreid',
            index=models.Index(fields=['created_by'], name='stores_rese_created_1e163c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservedstoreid',
            index=models.Index(fields=['is_active', 'keyword'], name='stores_rese_is_acti_12878a_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='stores_stor_is_acti_12939d_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['deleted_at'], name='stores_stor_deleted_6b7a54_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='stores_stor_created_f1ef67_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['updated_at'], name='stores_stor_updated_2d57d2_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_id', 'deleted_at'], name='stores_stor_store_i_91e114_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'deleted_at'], name='stores_stor_owner_i_0a1467_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'deleted_at'], name='stores_stor_is_acti_bd57e0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'deleted_at', 'created_at'], name='stores_stor_is_acti_d6288c_idx'),
        ),
        migrations.AddIndex(
            model_name='storecreationstep',
            index=models.Index(fields=['store'], name='stores_stor_store_i_5aa43e_idx'),
        ),
        migrations.AddIndex(
            model_name='storecreationstep',
            index=models.Index(fields=['current_step'], name='stores_stor_current_a11c27_idx'),
        ),
        migrations.AddIndex(
            model_name='storecreationstep',
            index=models.Index(fields=['created_at'], name='stores_stor_created_679f39_idx'),
        ),
        migrations.AddIndex(
            model_name='storecreationstep',
            index=models.Index(fields=['updated_at'], name='stores_stor_updated_2f6459_idx'),
        ),
    ]
