# Generated by Django 5.2.2 on 2025-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_reservedstoreid_stores_rese_keyword_695525_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_license_number',
            field=models.CharField(blank=True, help_text='사업자등록번호', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='telecommunication_sales_number',
            field=models.CharField(blank=True, help_text='통신판매업번호', max_length=50),
        ),
    ]
