# Generated by Django 5.2.2 on 2025-06-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_store_business_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='이메일 발송 기능 활성화'),
        ),
        migrations.AddField(
            model_name='store',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='발신자 이름 (기본값: 스토어명)', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='email_host_password_encrypted',
            field=models.TextField(blank=True, help_text='암호화된 Gmail 앱 비밀번호'),
        ),
        migrations.AddField(
            model_name='store',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Gmail 이메일 주소', max_length=254),
        ),
    ]
