# Generated by Django 5.2.2 on 2025-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_add_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='completion_message',
            field=models.TextField(blank=True, help_text='결제 완료 후 고객에게 보여줄 기본 안내 메시지'),
        ),
    ]
