# Generated by Django 5.2.2 on 2025-09-25 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_store_shipping_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['email_enabled'], name='stores_stor_email_e_ff14a6_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['email_enabled', 'deleted_at'], name='stores_stor_email_e_935914_idx'),
        ),
    ]
