# Generated by Django 5.2.2 on 2025-10-06 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_store_stores_stor_email_e_ff14a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BahPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='매장 이름', max_length=120)),
                ('postal_code', models.CharField(blank=True, help_text='우편번호', max_length=10)),
                ('address', models.CharField(help_text='매장 주소', max_length=255)),
                ('address_detail', models.CharField(blank=True, help_text='상세 주소', max_length=255)),
                ('phone_number', models.CharField(help_text='매장 연락처', max_length=30)),
                ('email', models.EmailField(help_text='홍보 관련 연락 이메일', max_length=254)),
                ('introduction', models.TextField(help_text='매장 소개')),
                ('lightning_public_key', models.CharField(blank=True, help_text='라이트닝 인증 공개키', max_length=66)),
                ('lightning_verified_at', models.DateTimeField(blank=True, help_text='라이트닝 인증 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bah_promotion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BAH 홍보 요청',
                'verbose_name_plural': 'BAH 홍보 요청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BahPromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_url', models.URLField(max_length=800, verbose_name='파일 URL')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기 (bytes)')),
                ('width', models.PositiveIntegerField(default=1000, verbose_name='이미지 너비')),
                ('height', models.PositiveIntegerField(default=563, verbose_name='이미지 높이')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
                ('promotion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.bahpromotionrequest')),
            ],
            options={
                'verbose_name': 'BAH 홍보 이미지',
                'verbose_name_plural': 'BAH 홍보 이미지',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bahpromotionrequest',
            index=models.Index(fields=['created_at'], name='stores_bahp_created_ec1880_idx'),
        ),
        migrations.AddIndex(
            model_name='bahpromotionrequest',
            index=models.Index(fields=['updated_at'], name='stores_bahp_updated_eee708_idx'),
        ),
        migrations.AddIndex(
            model_name='bahpromotionrequest',
            index=models.Index(fields=['user'], name='stores_bahp_user_id_32e906_idx'),
        ),
        migrations.AddIndex(
            model_name='bahpromotionimage',
            index=models.Index(fields=['promotion_request', 'order'], name='stores_bahp_promoti_5b129a_idx'),
        ),
        migrations.AddIndex(
            model_name='bahpromotionimage',
            index=models.Index(fields=['uploaded_at'], name='stores_bahp_uploade_6bbbfb_idx'),
        ),
    ]
