# Generated by Django 5.2.2 on 2025-10-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_bahpromotionrequest_bahpromotionimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bahpromotionrequest',
            name='shipping_status',
            field=models.CharField(choices=[('pending', '발송예정'), ('shipped', '발송')], default='pending', help_text='홍보 패키지 발송 상태', max_length=16),
        ),
        migrations.CreateModel(
            name='BahPromotionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bah_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BAH 관리자',
                'verbose_name_plural': 'BAH 관리자',
            },
        ),
    ]
