# Generated by Django 5.2.2 on 2025-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_bahpromotionrequest_shipping_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahPromotionLinkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_guide_url', models.URLField(blank=True, help_text='월오사 라이트닝 로그인 사용법 문서 링크')),
                ('usage_guide_url', models.URLField(blank=True, help_text='월오사 사용법 상세 문서 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BAH 링크 설정',
                'verbose_name_plural': 'BAH 링크 설정',
            },
        ),
    ]
