# Generated by Django 5.2.2 on 2025-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_bahpromotionlinksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahpromotionlinksettings',
            name='package_request_url',
            field=models.URLField(blank=True, help_text='홍보 패키지 신청 링크 (예: 사토샵 상품 페이지)'),
        ),
    ]
