# Generated by Django 5.2.2 on 2025-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_bahpromotionlinksettings_email_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahpromotionlinksettings',
            name='email_store_id',
            field=models.CharField(blank=True, help_text='이메일 설정 스토어 아이디: 입력된 스토어의 이메일 발송 설정을 사용해 홍보요청 내용을 메일로 전송합니다.', max_length=50),
        ),
    ]
