# Generated by Django 5.2.2 on 2025-11-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_alter_bahpromotionlinksettings_email_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', '상품'), ('meetup', '밋업'), ('live_lecture', '라이브 강의'), ('digital_file', '디지털 파일')], max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='연결된 객체 PK')),
                ('order', models.PositiveIntegerField(default=0, help_text='해당 타입 내 노출 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='stores.store')),
            ],
            options={
                'verbose_name': '스토어 노출 항목',
                'verbose_name_plural': '스토어 노출 항목',
                'ordering': ['item_type', 'order', 'created_at'],
                'indexes': [models.Index(fields=['store', 'item_type'], name='stores_stor_store_i_210c91_idx'), models.Index(fields=['item_type', 'order'], name='stores_stor_item_ty_62c174_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'item_type', 'object_id'), name='store_featured_unique_item'), models.UniqueConstraint(fields=('store', 'item_type', 'order'), name='store_featured_unique_order')],
            },
        ),
    ]
