# Generated by Django 5.2.2 on 2025-06-12 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0020_remove_cart_user_remove_cartitem_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니들',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='옵션ID: 선택지ID 형태로 저장', verbose_name='선택된 옵션들')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': '장바구니 아이템',
                'verbose_name_plural': '장바구니 아이템들',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '주문 대기'), ('payment_pending', '결제 대기'), ('paid', '결제 완료'), ('shipped', '배송 중'), ('delivered', '배송 완료'), ('cancelled', '주문 취소'), ('refunded', '환불 완료')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='주문자 이름')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='주문자 연락처')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='주문자 이메일')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='주소')),
                ('shipping_detail_address', models.CharField(max_length=100, verbose_name='상세주소')),
                ('order_memo', models.TextField(blank=True, verbose_name='주문 메모')),
                ('subtotal', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='상품 금액')),
                ('shipping_fee', models.PositiveIntegerField(help_text='원 단위', verbose_name='배송비')),
                ('total_amount', models.PositiveIntegerField(help_text='사토시 단위', verbose_name='총 금액')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='결제 ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_info_deleted_at', models.DateTimeField(blank=True, help_text='3개월 후 자동 삭제', null=True, verbose_name='개인정보 삭제 시간')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='상품명')),
                ('product_price', models.PositiveIntegerField(verbose_name='상품 가격')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('selected_options', models.JSONField(blank=True, default=dict, help_text='옵션명: 선택지명 형태로 저장', verbose_name='선택된 옵션들')),
                ('options_price', models.PositiveIntegerField(default=0, verbose_name='옵션 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': '주문 아이템',
                'verbose_name_plural': '주문 아이템들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='스토어명')),
                ('total_amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('purchase_date', models.DateTimeField(verbose_name='구매 날짜')),
                ('auto_delete_at', models.DateTimeField(help_text='구매 후 3개월 뒤 자동 삭제', verbose_name='자동 삭제 예정일')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구매 내역',
                'verbose_name_plural': '구매 내역들',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'created_at'], name='orders_orde_store_i_8955ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['user', 'purchase_date'], name='orders_purc_user_id_e9db58_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['auto_delete_at'], name='orders_purc_auto_de_395acc_idx'),
        ),
    ]
