# Generated by Django 5.2.2 on 2025-06-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0020_remove_cart_user_remove_cartitem_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_hash', models.CharField(max_length=100, unique=True, verbose_name='결제 해시')),
                ('invoice_string', models.TextField(verbose_name='인보이스 문자열')),
                ('amount_sats', models.PositiveIntegerField(verbose_name='금액(사토시)')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('paid', '결제 완료'), ('expired', '만료됨'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order', verbose_name='주문')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stores.store', verbose_name='스토어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '인보이스',
                'verbose_name_plural': '인보이스들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_hash'], name='orders_invo_payment_0a8ed7_idx'), models.Index(fields=['status', 'created_at'], name='orders_invo_status_ff302a_idx'), models.Index(fields=['user', 'status'], name='orders_invo_user_id_87b30a_idx'), models.Index(fields=['store', 'status'], name='orders_invo_store_i_e0fb78_idx')],
            },
        ),
    ]
