# Generated by Django 5.2.2 on 2025-06-17 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice'),
        ('products', '0007_remove_productoption_products_unique_product_option_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='orders_cart_user_id_7d3dad_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='orders_cart_created_50584e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='orders_cart_updated_c19f83_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='orders_cart_cart_id_dc9f49_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='orders_cart_product_81483c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='orders_cart_added_a_a6c368_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['updated_at'], name='orders_cart_updated_c4de4e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='orders_cart_cart_id_dd7f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='orders_cart_cart_id_cb3fba_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['created_at'], name='orders_orde_created_861eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4ba133_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['user'], name='orders_purc_user_id_24e831_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['purchase_date'], name='orders_purc_purchas_e03107_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['order'], name='orders_purc_order_i_01c7e3_idx'),
        ),
    ]
