# Generated by Django migration for order number format update

from django.db import migrations
import uuid


def update_order_number_format(apps, schema_editor):
    """기존 주문번호를 새로운 형식으로 업데이트: store_id-ord-YYMM-해시값"""
    Order = apps.get_model('orders', 'Order')
    
    # 모든 주문을 가져와서 생성일시 순으로 정렬
    orders = Order.objects.select_related('store').all().order_by('created_at')
    
    updated_count = 0
    for order in orders:
        try:
            # 새로운 주문번호 생성
            created_at = order.created_at
            store_id = order.store.store_id
            year_month = created_at.strftime('%y%m')  # 2501 형식
            hash_value = str(uuid.uuid4())[:8].upper()
            
            new_order_number = f"{store_id}-ord-{year_month}-{hash_value}"
            
            # 중복 확인 및 처리
            counter = 0
            original_new_order_number = new_order_number
            
            while Order.objects.filter(order_number=new_order_number).exists():
                counter += 1
                # 중복이 있으면 새로운 해시값 생성
                hash_value = str(uuid.uuid4())[:8].upper()
                new_order_number = f"{store_id}-ord-{year_month}-{hash_value}"
                
                # 무한루프 방지
                if counter > 100:
                    break
            
            # 주문번호 업데이트
            old_order_number = order.order_number
            order.order_number = new_order_number
            order.save(update_fields=['order_number'])
            
            updated_count += 1
            print(f"Updated Order {order.id}: {old_order_number} -> {new_order_number}")
            
        except Exception as e:
            print(f"Error updating Order {order.id}: {str(e)}")
            continue
    
    print(f"Total updated orders: {updated_count}")


def reverse_order_number_format(apps, schema_editor):
    """역마이그레이션은 지원하지 않음 (데이터 손실 위험)"""
    print("Warning: 주문번호 형식 변경의 역마이그레이션은 지원하지 않습니다.")
    print("기존 주문번호 정보가 손실될 수 있습니다.")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_number_format'),
    ]

    operations = [
        migrations.RunPython(
            update_order_number_format,
            reverse_order_number_format,
        ),
    ] 