# Generated by Django 5.2.2 on 2025-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='frozen_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='장바구니 추가 시점의 BTC/KRW 환율', max_digits=15, null=True, verbose_name='고정 환율'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='frozen_options_price_sats',
            field=models.PositiveIntegerField(default=0, help_text='장바구니 추가 시점의 옵션 사토시 가격', verbose_name='고정 옵션 가격(사토시)'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='frozen_product_price_sats',
            field=models.PositiveIntegerField(blank=True, help_text='장바구니 추가 시점의 사토시 가격', null=True, verbose_name='고정 상품 가격(사토시)'),
        ),
    ]
