# Generated by Django 5.2.2 on 2025-07-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_number_format'),
        ('orders', '0005_cartitem_frozen_exchange_rate_and_more'),
    ]

    operations = [
    ]
