# Generated by Django 5.2.2 on 2025-07-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_update_order_number_to_new_format'),
        ('orders', '0006_merge_20250707_0833'),
    ]

    operations = [
    ]
