# Generated by Django 5.2.2 on 2025-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_update_order_number_format_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('preparing', '배송준비중'), ('completed', '배송완료')], default='preparing', max_length=20, verbose_name='배송 상태'),
        ),
    ]
