# Generated by Django 5.2.2 on 2025-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='택배사명'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='송장번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('preparing', '발송준비중'), ('completed', '발송완료')], default='preparing', max_length=20, verbose_name='발송 상태'),
        ),
    ]
