# Generated by Django 5.2.2 on 2025-09-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_user_status_indexes'),
        ('stores', '0025_store_shipping_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='auto_delete_at',
            field=models.DateTimeField(help_text='구매 후 1년 뒤 자동 삭제', verbose_name='자동 삭제 예정일'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
