# Generated by Django 5.2.2 on 2025-09-25 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_purchasehistory_auto_delete_at_and_more'),
        ('stores', '0026_store_stores_stor_email_e_ff14a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'status', '-created_at'], name='invoice_store_stat_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['expires_at'], name='orders_invo_expires_5e1417_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_status', '-created_at'], name='orders_deliv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', '-created_at'], name='orders_store_stat_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_status'], name='orders_orde_deliver_b8914b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('paid_at__isnull', False)), fields=['paid_at'], name='orders_paid_not_null_idx'),
        ),
    ]
