# Generated by Django 5.2.2 on 2025-11-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln_payment', '0005_paymenttransaction_file_order'),
        ('orders', '0013_invoice_invoice_store_stat_cr_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManualPaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '수동 저장 결제',
                'verbose_name_plural': '수동 저장 결제',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.manualpaymenttransaction',),
        ),
        migrations.CreateModel(
            name='ProductOrderItemReservation',
            fields=[
            ],
            options={
                'verbose_name': '재고 예약',
                'verbose_name_plural': '재고 예약',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.orderitemreservation',),
        ),
        migrations.CreateModel(
            name='ProductPaymentStageLog',
            fields=[
            ],
            options={
                'verbose_name': '결제 단계 로그',
                'verbose_name_plural': '결제 단계 로그',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymentstagelog',),
        ),
        migrations.CreateModel(
            name='ProductPaymentTransaction',
            fields=[
            ],
            options={
                'verbose_name': '결제 트랜잭션',
                'verbose_name_plural': '결제 트랜잭션',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ln_payment.paymenttransaction',),
        ),
    ]
