# Generated by Django 5.2.2 on 2025-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_productmanualpaymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('preparing', '발송준비중'), ('completed', '발송완료'), ('pickup', '현장 수령')], default='preparing', max_length=20, verbose_name='발송 상태'),
        ),
    ]
