# Generated by Django 5.2.2 on 2025-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.SlugField(blank=True, help_text='주문 유입 채널 (예: web, api-partner-a)'),
        ),
    ]
