# Generated by Django 5.2.2 on 2025-06-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0, help_text='원 단위', verbose_name='배송비'),
        ),
    ]
