# Generated by Django 5.2.2 on 2025-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0, help_text='가격표시방식에 따라 원 또는 사토시 단위', verbose_name='배송비'),
        ),
    ]
