# Generated by Django 5.2.2 on 2025-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price_krw',
            field=models.PositiveIntegerField(blank=True, help_text='원화 단위', null=True, verbose_name='원화 할인가격'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_krw',
            field=models.PositiveIntegerField(blank=True, help_text='원화 단위', null=True, verbose_name='원화 가격'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee_krw',
            field=models.PositiveIntegerField(blank=True, help_text='원화 단위', null=True, verbose_name='원화 배송비'),
        ),
    ]
