# Generated by Django 5.2.2 on 2025-06-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discounted_price_krw_product_price_krw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptionchoice',
            name='price_krw',
            field=models.IntegerField(blank=True, help_text='원화 단위', null=True, verbose_name='원화 추가 가격'),
        ),
    ]
