# Generated by Django 5.2.2 on 2025-06-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productoptionchoice_price_krw'),
        ('stores', '0021_reservedstoreid_stores_rese_keyword_695525_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoption',
            name='products_unique_product_option_name',
        ),
        migrations.RemoveConstraint(
            model_name='productoptionchoice',
            name='products_unique_option_choice_name',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store'], name='products_pr_store_i_07a248_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_discounted'], name='products_pr_is_disc_7e131a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_display'], name='products_pr_price_d_3fa37c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='products_pr_updated_150263_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active', 'created_at'], name='products_pr_store_i_fc5234_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='products_pr_is_acti_defdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'created_at'], name='products_pr_store_i_59644a_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product'], name='products_pr_product_aa9685_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['order'], name='products_pr_order_83053c_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['created_at'], name='products_pr_created_c34aec_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_a98bda_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionchoice',
            index=models.Index(fields=['option'], name='products_pr_option__d73e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionchoice',
            index=models.Index(fields=['order'], name='products_pr_order_2379a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionchoice',
            index=models.Index(fields=['created_at'], name='products_pr_created_56c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionchoice',
            index=models.Index(fields=['option', 'order'], name='products_pr_option__9a7197_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionchoice',
            index=models.Index(fields=['price'], name='products_pr_price_e78a3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_option_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productoptionchoice',
            constraint=models.UniqueConstraint(fields=('option', 'name'), name='unique_choice_per_option'),
        ),
    ]
