# Generated by Django 5.2.2 on 2025-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_temporarily_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='일시품절'),
        ),
    ]
