# Generated by Django 5.2.2 on 2025-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_force_free_shipping'),
        ('stores', '0026_store_stores_stor_email_e_ff14a6_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_temporarily_out_of_stock'], name='products_pr_is_temp_5ca076_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_temporarily_out_of_stock'], name='products_pr_store_i_d25416_idx'),
        ),
    ]
