# Generated by Django 5.2.2 on 2025-10-02 23:37

from django.db import migrations


DEFAULT_CATEGORY_NAME = '카테고리 없음'


def forwards(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Product = apps.get_model('products', 'Product')
    ProductCategory = apps.get_model('products', 'ProductCategory')

    store_to_category = {}

    for store in Store.objects.all():
        category, _created = ProductCategory.objects.get_or_create(
            store=store,
            name=DEFAULT_CATEGORY_NAME,
            defaults={'order': 0},
        )
        store_to_category[store.pk] = category.pk

    products_to_update = []
    for product in Product.objects.filter(category__isnull=True).only('id', 'store_id'):
        default_category_id = store_to_category.get(product.store_id)
        if default_category_id:
            product.category_id = default_category_id
            products_to_update.append(product)

    if products_to_update:
        Product.objects.bulk_update(products_to_update, ['category'])


def backwards(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductCategory = apps.get_model('products', 'ProductCategory')

    default_categories = ProductCategory.objects.filter(name=DEFAULT_CATEGORY_NAME)
    Product.objects.filter(category__in=default_categories).update(category=None)
    default_categories.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategory_product_category_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
